/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemEvents]

/* ------------------------------------------------------------
   Get rid of obsolete InsertAssetTracking
   Get rid of obsolete UpdateAssetTracking
   Get rid of obsolete DeleteAssetTracking
   Get rid of obsolete SearchAssetTrackingByString
   Get rid of obsolete GetAssetTrackingByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertAssetTracking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertAssetTracking;
        PRINT 'Dropped InsertAssetTracking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateAssetTracking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateAssetTracking;
        PRINT 'Dropped UpdateAssetTracking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteAssetTracking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteAssetTracking;
        PRINT 'Dropped DeleteAssetTracking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchAssetTrackingByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchAssetTrackingByString;
        PRINT 'Dropped SearchAssetTrackingByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetAssetTrackingByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetAssetTrackingByID;
        PRINT 'Dropped GetAssetTrackingByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__AssetTracking_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__AssetTracking_GetByID;
        PRINT 'Dropped spGen__AssetTracking_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__AssetTracking_GetByID

   Description:  Selects record(s) from table 'AssetTracking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__AssetTracking_GetByID
(
    @AssetTrackingID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [AssetTrackingID],[AssetID],[TractingAction],[SendToAddress],[SendToRheemEventID],[TrackingNumber],[CreateDate],[CreateBy]
    FROM [AssetTracking]
    WHERE [AssetTrackingID] = @AssetTrackingID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__AssetTracking_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__AssetTracking_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__AssetTracking_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__AssetTracking_SearchByString;
        PRINT 'Dropped spGen__AssetTracking_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__AssetTracking_SearchByString

   Description:  Selects a record from table 'AssetTracking'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__AssetTracking_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [AssetTrackingID],[AssetID],[TractingAction],[SendToAddress],[SendToRheemEventID],[TrackingNumber],[CreateDate],[CreateBy]
    FROM [AssetTracking]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__AssetTracking_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__AssetTracking_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__AssetTracking_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__AssetTracking_Delete;
        PRINT 'Dropped spGen__AssetTracking_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__AssetTracking_Delete

   Description:  Deletes a record from table 'AssetTracking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__AssetTracking_Delete
(
    @AssetTrackingID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [AssetTracking]
    WHERE [AssetTrackingID] = @AssetTrackingID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__AssetTracking_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__AssetTracking_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__AssetTracking_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__AssetTracking_Save;
        PRINT 'Dropped spGen__AssetTracking_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__AssetTracking_Save

   Description:  Updates or Deletes a record In table 'AssetTracking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__AssetTracking_Save
(
    @ErrText varchar(4000) output,
    @AssetTrackingID uniqueidentifier output,
    @AssetID uniqueidentifier,
    @TractingAction varchar(150),
    @SendToAddress nvarchar(350),
    @SendToRheemEventID uniqueidentifier,
    @TrackingNumber varchar(50),
    @CreateDate smalldatetime,
    @CreateBy uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @AssetTrackingID = '00000000-0000-0000-0000-000000000000' SET @AssetTrackingID = NULL
    IF @AssetTrackingID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @AssetTrackingID = NewID()

                    INSERT
                    INTO [AssetTracking]
                    (
                        [AssetTrackingID],
                        [AssetID],
                        [TractingAction],
                        [SendToAddress],
                        [SendToRheemEventID],
                        [TrackingNumber],
                        [CreateDate],
                        [CreateBy]
                    )
                    VALUES
                    (
                        @AssetTrackingID,
                        @AssetID,
                        @TractingAction,
                        @SendToAddress,
                        @SendToRheemEventID,
                        @TrackingNumber,
                        @CreateDate,
                        @CreateBy
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [AssetTracking]
                    SET
                    [AssetID] = @AssetID,
                    [TractingAction] = @TractingAction,
                    [SendToAddress] = @SendToAddress,
                    [SendToRheemEventID] = @SendToRheemEventID,
                    [TrackingNumber] = @TrackingNumber,
                    [CreateDate] = @CreateDate,
                    [CreateBy] = @CreateBy
                    WHERE [AssetTrackingID] = @AssetTrackingID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__AssetTracking_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__AssetTracking_Save Error on Creation'
GO




