/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemEvents]

/* ------------------------------------------------------------
   Get rid of obsolete InsertRheemEventPerson
   Get rid of obsolete UpdateRheemEventPerson
   Get rid of obsolete DeleteRheemEventPerson
   Get rid of obsolete SearchRheemEventPersonByString
   Get rid of obsolete GetRheemEventPersonByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertRheemEventPerson') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertRheemEventPerson;
        PRINT 'Dropped InsertRheemEventPerson'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateRheemEventPerson') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateRheemEventPerson;
        PRINT 'Dropped UpdateRheemEventPerson'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteRheemEventPerson') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteRheemEventPerson;
        PRINT 'Dropped DeleteRheemEventPerson'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchRheemEventPersonByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchRheemEventPersonByString;
        PRINT 'Dropped SearchRheemEventPersonByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetRheemEventPersonByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetRheemEventPersonByID;
        PRINT 'Dropped GetRheemEventPersonByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventPerson_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventPerson_GetByID;
        PRINT 'Dropped spGen__RheemEventPerson_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventPerson_GetByID

   Description:  Selects record(s) from table 'RheemEventPerson'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventPerson_GetByID
(
    @RheemEventPersonID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [RheemEventPersonID],[RheemEventID],[PersonID],[PersonRole],[ShirtSize],[PantSize],[ShoeSize]
    FROM [RheemEventPerson]
    WHERE [RheemEventPersonID] = @RheemEventPersonID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventPerson_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventPerson_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventPerson_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventPerson_SearchByString;
        PRINT 'Dropped spGen__RheemEventPerson_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventPerson_SearchByString

   Description:  Selects a record from table 'RheemEventPerson'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventPerson_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [RheemEventPersonID],[RheemEventID],[PersonID],[PersonRole],[ShirtSize],[PantSize],[ShoeSize]
    FROM [RheemEventPerson]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventPerson_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventPerson_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventPerson_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventPerson_Delete;
        PRINT 'Dropped spGen__RheemEventPerson_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventPerson_Delete

   Description:  Deletes a record from table 'RheemEventPerson'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventPerson_Delete
(
    @RheemEventPersonID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [RheemEventPerson]
    WHERE [RheemEventPersonID] = @RheemEventPersonID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventPerson_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventPerson_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventPerson_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventPerson_Save;
        PRINT 'Dropped spGen__RheemEventPerson_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventPerson_Save

   Description:  Updates or Deletes a record In table 'RheemEventPerson'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventPerson_Save
(
    @ErrText varchar(4000) output,
    @RheemEventPersonID uniqueidentifier output,
    @RheemEventID uniqueidentifier,
    @PersonID uniqueidentifier,
    @PersonRole varchar(50),
    @ShirtSize varchar(50),
    @PantSize varchar(50),
    @ShoeSize varchar(50)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @RheemEventPersonID = '00000000-0000-0000-0000-000000000000' SET @RheemEventPersonID = NULL
    IF @RheemEventPersonID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @RheemEventPersonID = NewID()

                    INSERT
                    INTO [RheemEventPerson]
                    (
                        [RheemEventPersonID],
                        [RheemEventID],
                        [PersonID],
                        [PersonRole],
                        [ShirtSize],
                        [PantSize],
                        [ShoeSize]
                    )
                    VALUES
                    (
                        @RheemEventPersonID,
                        @RheemEventID,
                        @PersonID,
                        @PersonRole,
                        @ShirtSize,
                        @PantSize,
                        @ShoeSize
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [RheemEventPerson]
                    SET
                    [RheemEventID] = @RheemEventID,
                    [PersonID] = @PersonID,
                    [PersonRole] = @PersonRole,
                    [ShirtSize] = @ShirtSize,
                    [PantSize] = @PantSize,
                    [ShoeSize] = @ShoeSize
                    WHERE [RheemEventPersonID] = @RheemEventPersonID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventPerson_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventPerson_Save Error on Creation'
GO




