/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemEvents]

/* ------------------------------------------------------------
   Get rid of obsolete InsertRheemEventDetail
   Get rid of obsolete UpdateRheemEventDetail
   Get rid of obsolete DeleteRheemEventDetail
   Get rid of obsolete SearchRheemEventDetailByString
   Get rid of obsolete GetRheemEventDetailByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertRheemEventDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertRheemEventDetail;
        PRINT 'Dropped InsertRheemEventDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateRheemEventDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateRheemEventDetail;
        PRINT 'Dropped UpdateRheemEventDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteRheemEventDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteRheemEventDetail;
        PRINT 'Dropped DeleteRheemEventDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchRheemEventDetailByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchRheemEventDetailByString;
        PRINT 'Dropped SearchRheemEventDetailByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetRheemEventDetailByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetRheemEventDetailByID;
        PRINT 'Dropped GetRheemEventDetailByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventDetail_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventDetail_GetByID;
        PRINT 'Dropped spGen__RheemEventDetail_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventDetail_GetByID

   Description:  Selects record(s) from table 'RheemEventDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventDetail_GetByID
(
    @RheemEventDetailID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [RheemEventDetailID],[RheemEventID],[ShowSchedule],[ShowObjectives],[ShowTactics],[Sponsorships],[AdvertisingSupport],[WebsiteSupport],[ResultsAndMeasures],[AttendanceCriteria],[EventMgmtContactOrganizationID],[EventMgmtContactPersonID],[EventMgmtContactPhone],[EventMgmtContactEmail],[EmployeeEventFloorContactID]
    FROM [RheemEventDetail]
    WHERE [RheemEventDetailID] = @RheemEventDetailID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventDetail_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventDetail_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventDetail_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventDetail_SearchByString;
        PRINT 'Dropped spGen__RheemEventDetail_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventDetail_SearchByString

   Description:  Selects a record from table 'RheemEventDetail'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventDetail_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [RheemEventDetailID],[RheemEventID],[ShowSchedule],[ShowObjectives],[ShowTactics],[Sponsorships],[AdvertisingSupport],[WebsiteSupport],[ResultsAndMeasures],[AttendanceCriteria],[EventMgmtContactOrganizationID],[EventMgmtContactPersonID],[EventMgmtContactPhone],[EventMgmtContactEmail],[EmployeeEventFloorContactID]
    FROM [RheemEventDetail]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventDetail_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventDetail_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventDetail_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventDetail_Delete;
        PRINT 'Dropped spGen__RheemEventDetail_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventDetail_Delete

   Description:  Deletes a record from table 'RheemEventDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventDetail_Delete
(
    @RheemEventDetailID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [RheemEventDetail]
    WHERE [RheemEventDetailID] = @RheemEventDetailID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventDetail_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventDetail_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemEventDetail_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemEventDetail_Save;
        PRINT 'Dropped spGen__RheemEventDetail_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemEventDetail_Save

   Description:  Updates or Deletes a record In table 'RheemEventDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemEventDetail_Save
(
    @ErrText varchar(4000) output,
    @RheemEventDetailID uniqueidentifier output,
    @RheemEventID uniqueidentifier,
    @ShowSchedule ntext,
    @ShowObjectives ntext,
    @ShowTactics ntext,
    @Sponsorships ntext,
    @AdvertisingSupport ntext,
    @WebsiteSupport ntext,
    @ResultsAndMeasures ntext,
    @AttendanceCriteria ntext,
    @EventMgmtContactOrganizationID uniqueidentifier,
    @EventMgmtContactPersonID uniqueidentifier,
    @EventMgmtContactPhone varchar(50),
    @EventMgmtContactEmail varchar(150),
    @EmployeeEventFloorContactID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @RheemEventDetailID = '00000000-0000-0000-0000-000000000000' SET @RheemEventDetailID = NULL
    IF @RheemEventDetailID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @RheemEventDetailID = NewID()

                    INSERT
                    INTO [RheemEventDetail]
                    (
                        [RheemEventDetailID],
                        [RheemEventID],
                        [ShowSchedule],
                        [ShowObjectives],
                        [ShowTactics],
                        [Sponsorships],
                        [AdvertisingSupport],
                        [WebsiteSupport],
                        [ResultsAndMeasures],
                        [AttendanceCriteria],
                        [EventMgmtContactOrganizationID],
                        [EventMgmtContactPersonID],
                        [EventMgmtContactPhone],
                        [EventMgmtContactEmail],
                        [EmployeeEventFloorContactID]
                    )
                    VALUES
                    (
                        @RheemEventDetailID,
                        @RheemEventID,
                        @ShowSchedule,
                        @ShowObjectives,
                        @ShowTactics,
                        @Sponsorships,
                        @AdvertisingSupport,
                        @WebsiteSupport,
                        @ResultsAndMeasures,
                        @AttendanceCriteria,
                        @EventMgmtContactOrganizationID,
                        @EventMgmtContactPersonID,
                        @EventMgmtContactPhone,
                        @EventMgmtContactEmail,
                        @EmployeeEventFloorContactID
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [RheemEventDetail]
                    SET
                    [RheemEventID] = @RheemEventID,
                    [ShowSchedule] = @ShowSchedule,
                    [ShowObjectives] = @ShowObjectives,
                    [ShowTactics] = @ShowTactics,
                    [Sponsorships] = @Sponsorships,
                    [AdvertisingSupport] = @AdvertisingSupport,
                    [WebsiteSupport] = @WebsiteSupport,
                    [ResultsAndMeasures] = @ResultsAndMeasures,
                    [AttendanceCriteria] = @AttendanceCriteria,
                    [EventMgmtContactOrganizationID] = @EventMgmtContactOrganizationID,
                    [EventMgmtContactPersonID] = @EventMgmtContactPersonID,
                    [EventMgmtContactPhone] = @EventMgmtContactPhone,
                    [EventMgmtContactEmail] = @EventMgmtContactEmail,
                    [EmployeeEventFloorContactID] = @EmployeeEventFloorContactID
                    WHERE [RheemEventDetailID] = @RheemEventDetailID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemEventDetail_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemEventDetail_Save Error on Creation'
GO




