USE support;

CREATE TABLE IF NOT EXISTS appdomain ( 
	AppDomainId int(11) NOT NULL AUTO_INCREMENT, 
	DomainName varchar(255) NOT NULL, 
	DomainPrefix varchar(10) NOT NULL, 
	CreateDateTime__Gen DATETIME NOT NULL, 
	UpdateDateTime__Gen DATETIME NOT NULL, 
	PRIMARY KEY (AppDomainId), 
	UNIQUE INDEX applicationdomain_idx1 (DomainName) 
); 

INSERT IGNORE INTO appdomain SET AppDomainId = 1, DomainName = 'EcoNet', DomainPrefix = 'eco', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO appdomain SET AppDomainId = 2, DomainName = 'EcoNet Admin', DomainPrefix = 'admineco', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO appdomain SET AppDomainId = 3, DomainName = 'Public', DomainPrefix = 'public', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO appdomain SET AppDomainId = 4, DomainName = 'Partners', DomainPrefix = 'partners', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();

DROP TABLE IF EXISTS routedefinition;

CREATE TABLE IF NOT EXISTS routedefinition (
    RouteDefinitionId int(11) NOT NULL AUTO_INCREMENT,
	RouteUrl varchar(255) NOT NULL,
	ControllerName varchar(255) NOT NULL,
	HttpMethod varchar(10) NOT NULL,
	IsPublic bit NOT NULL DEFAULT 0,
	IsAdminOnly bit NOT NULL DEFAULT 0,
	IsBasicAuth bit NOT NULL DEFAULT 0,
	IsBearerTokenAuth bit NOT NULL DEFAULT 0,
	RequiresReplayProtection bit NOT NULL DEFAULT 0,
	RequiresAuthorization bit NOT NULL DEFAULT 0,
	TableToAuthorize varchar(255) NULL,
	IsLoggingEnabled bit NOT NULL DEFAULT 0,
	CreateDateTime__Gen DATETIME NOT NULL,
    UpdateDateTime__Gen DATETIME NOT NULL,
	PRIMARY KEY (RouteDefinitionId),
	UNIQUE INDEX routedefinition_idx1 (RouteUrl, HttpMethod)
);

TRUNCATE TABLE routedefinition;

call rheem.AddColumnIfNotExists('support', 'routedefinition', 'AppDomainId',  'int NOT NULL');

call rheem.CreateForeignKeyIfNotExists('support', 'routedefinitionFK1', 'routedefinition', 'AppDomainId', 'appdomain', 'AppDomainId', 'dropAndReplace', 'ON DELETE CASCADE');		

INSERT IGNORE INTO routedefinition SET ControllerName = 'UserLocationsController', RouteUrl = '/v1/eco/mylocations', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UserLocationsController', RouteUrl = '/v1/admineco/userlocations/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UserLocationsController', RouteUrl = '/v1/eco/mylocations', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UserLocationsController', RouteUrl = '/v1/eco/mylocations', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UserLocationsController', RouteUrl = '/v1/eco/changelocationname', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'TimeZonesController', RouteUrl = '/v1/public/timezones', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicPartnersAccountsController', RouteUrl = '/v1/public/requestpartnersaccount', HttpMethod = 'POST', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicPartnersAccountsController', RouteUrl = '/v1/public/requestpartnersaccount', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicPartnersAccountsController', RouteUrl = '/v1/public/forgotmyrheemusername', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicPartnersAccountsController', RouteUrl = '/v1/public/forgotmyrheempassword', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicPartnersAccountsController', RouteUrl = '/v1/public/resetmyrheempassword', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAdminController', RouteUrl = '/v1/admineco/equipment', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=2, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAdminController', RouteUrl = '/v1/admineco/equipment', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=2, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/myequipment/atlocation/{id}', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/myequipment', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/myequipmentcheck', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/myequipmentcheck/{id}', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v2/eco/myequipmentcheck', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v2/eco/myequipmentcheck/{id}', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/changeequipmentname', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/removeequipment/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentsController', RouteUrl = '/v1/eco/removelocation/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/savewhmode', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/savewhtemp', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v2/eco/myequipmentattributes/savewhmode', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v2/eco/myequipmentattributes/savewhtemp', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v2/eco/myequipmentattributes/genwrite', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v2/eco/myequipmentattributes/genread', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;


INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/saveacmode', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/saveacheattemp', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/saveaccooltemp', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAttributesController', RouteUrl = '/v1/eco/myequipmentattributes/buzzer', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipment', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;


INSERT IGNORE INTO routedefinition SET ControllerName = 'MessageQueuesController', RouteUrl = '/v1/admineco/msgqueuesize', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=2, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v1/eco/myunreadequipmentalerts', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v1/eco/myunreadequipmentalertcount', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v1/eco/myequipmentalerts', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v2/eco/myunreadequipmentalertcount', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v2/eco/myequipmentalerts', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v1/eco/markalertasdeleted', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='econet.equipmentalert', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'EquipmentAlertsController', RouteUrl = '/v1/eco/markalertasread', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.equipmentalert', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EcoNetAdminController', RouteUrl = '/v1/admineco/equipalert', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=2, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'VacationsController', RouteUrl = '/v1/eco/myvacations', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'VacationsController', RouteUrl = '/v1/eco/myvacations', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'VacationsController', RouteUrl = '/v1/eco/myvacations', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.vacation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'VacationsController', RouteUrl = '/v1/eco/getvacationsatlocation', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'VacationsController', RouteUrl = '/v1/eco/myvacations/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='econet.vacation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/authenticate', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 1, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/myuserinfo', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/myuserinfo', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/changeemail', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/createaccount', HttpMethod = 'POST', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/forgotpassword', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/changetempdisplaymode', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/getnetworklist', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/changename', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/changepassword', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/validatemacaddress', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v2/eco/validatemacaddress', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/addequipmenttoaccount', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.userlocation', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UsersController', RouteUrl = '/v1/eco/resetpassword', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorInfoesController', RouteUrl = '/v1/eco/mycontractors', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorInfoesController', RouteUrl = '/v1/eco/mycontractors', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorInfoesController', RouteUrl = '/v1/eco/mycontractors', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.contractorinfo', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorInfoesController', RouteUrl = '/v1/eco/mycontractors/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='econet.contractorinfo', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'UserMessagesController', RouteUrl = '/v1/eco/mynotifications', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'UserMessagesController', RouteUrl = '/v1/eco/mynotifications', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 1, TableToAuthorize='econet.usermessage', AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'UserDeviceTokenController', RouteUrl = '/v1/eco/devicetoken', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PartnersAuthenticationController', RouteUrl = '/v1/partners/authenticate', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 1, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicWarrantiesController', RouteUrl = '/v1/public/warranties/printcertificate', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicWarrantiesController', RouteUrl = '/v1/public/warranties/certificatefromextdata', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicWarrantiesController', RouteUrl = '/v1/public/warranties/validateserialnumber', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicWarrantiesController', RouteUrl = '/v1/public/warranties/registerunits', HttpMethod = 'POST', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicRefreshTokenController', RouteUrl = '/v1/public/tokens/refresh', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'EmailsController', RouteUrl = '/v1/partners/email/sendgenericemail', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 1, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/designstar/getperson', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='rheem.ru_person', AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/basic/getmyaccountinfo', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='rheem.ru_person', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/designstar/getrheememployee', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='rheem.ru_person', AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/designstar/getcontractor', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='rheem.ru_organization', AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/retail/getcontractor', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='rheem.ru_person', AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DesignStarController', RouteUrl = '/v1/partners/designstar/getdistributor', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, TableToAuthorize='rheem.ru_organization', AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'APILoggingController', RouteUrl = '/v1/partners/apilogs/recent1000', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'APILoggingController', RouteUrl = '/v1/partners/apilogs/routecounts', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'APILoggingController', RouteUrl = '/v1/partners/apilogs/routetiming', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'APILoggingController', RouteUrl = '/v1/partners/apilogs/routeexceptions', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'APILoggingController', RouteUrl = '/v1/partners/apilogs/exceptionsforoneroute', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'APIInfoController', RouteUrl = '/v1/partners/controllers', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicGlossariesController', RouteUrl = '/v1/public/glossaries', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'GlossariesController', RouteUrl = '/v1/partners/glossary', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='support.glossary', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'GlossariesController', RouteUrl = '/v1/partners/glossary', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='support.glossary', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'GlossariesController', RouteUrl = '/v1/partners/glossary', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'GlossariesController', RouteUrl = '/v1/partners/glossary/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='support.glossary', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'GlossariesController', RouteUrl = '/v1/partners/glossary/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='support.glossary', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'DivisionsController', RouteUrl = '/v1/partners/divisions', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'RheemWebSitesController', RouteUrl = '/v1/partners/websites', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'RheemWebSitesController', RouteUrl = '/v1/partners/getmenus', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'RheemWebSitesController', RouteUrl = '/v1/partners/getspecialpagebyid', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'RheemWebSitesController', RouteUrl = '/v1/partners/producttags', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicContractorsController', RouteUrl = '/v1/public/contractors/getcontractorsbyzipandradius', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicContractorsController', RouteUrl = '/v1/public/contractors/getraypakpsrepsbystate', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getproductbymodelnumber', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodels', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getbrands', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getbrandbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getcategories', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getcategoriesbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getseries', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getseriesbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodeldocumentsbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelimagesbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelcertificationsbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelnumbersbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelbadgesbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelpartsbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodelpartscomponents', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/literaturedescription', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicProductsController', RouteUrl = '/v1/public/products/getmodeltagsbyid', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ModelsController', RouteUrl = '/v1/public/products/modelwithmodelnumbers', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/pricingnames', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/designstar', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/distributorwithusers', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/distributorsbypostalcode', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/addresses', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/parents', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/distributors/branches', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorsbydistributor', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractors/contractor', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorassets', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorasset', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorasset', HttpMethod = 'PUT', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='rheem.organizationasset', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorasset', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'ContractorsController', RouteUrl = '/v1/partners/contractorasset/{id}', HttpMethod = 'DELETE', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 1, AppDomainId=4, TableToAuthorize='rheem.organizationasset', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'SupportController', RouteUrl = '/v1/partners/helpdesktickets/ticketsbymonth', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'SupportController', RouteUrl = '/v1/partners/helpdesktickets/ticketsbycategory', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'LoadOrgsController', RouteUrl = '/v1/partners/loadorgs', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 1, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'HDOrderController', RouteUrl = '/v1/partners/searchhdorder', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'HDOrderController', RouteUrl = '/v1/partners/getfullhdorder', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'HDOrderController', RouteUrl = '/v1/partners/gethdmodelsbymodeltype', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'HDOrderController', RouteUrl = '/v1/partners/savehdorder', HttpMethod = 'POST', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'DistributorsController', RouteUrl = '/v1/partners/contractor/preferred/retail', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicCatalogController', RouteUrl = '/v1/public/catalogaddendums', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'AdmakerController', RouteUrl = '/v1/partners/admaker', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'AdmakerController', RouteUrl = '/v1/partners/admakerimages', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'AdmakerController', RouteUrl = '/v1/partners/admakerads', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'AdmakerController', RouteUrl = '/v1/partners/admakerad', HttpMethod = 'GET', IsPublic=0, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 1, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;

INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicAHRIController', RouteUrl = '/v1/ahri/getoutdoormodellist', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicAHRIController', RouteUrl = '/v1/ahri/getindoormodellist', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicAHRIController', RouteUrl = '/v1/ahri/getfurnacemodellist', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;
INSERT IGNORE INTO routedefinition SET ControllerName = 'PublicAHRIController', RouteUrl = '/v1/ahri/getahridata', HttpMethod = 'GET', IsPublic=1, IsAdminOnly = 0, IsBasicAuth = 0, IsBearerTokenAuth = 0, RequiresReplayProtection = 0, RequiresAuthorization = 0, AppDomainId=3, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW(), IsLoggingEnabled = 1;


CREATE TABLE IF NOT EXISTS clientapplication ( 
	ClientApplicationId int(11) NOT NULL AUTO_INCREMENT, 
	ClientId varchar(255) NOT NULL, 
	BearerTokenProvider varchar(255) NOT NULL,  
	ApplicationName varchar(255) NOT NULL, 
	ProjectName varchar(255) NOT NULL,
	EmailAddress varchar(255) NOT NULL, 
	CreateDateTime__Gen DATETIME NOT NULL, 
	UpdateDateTime__Gen DATETIME NOT NULL, 
	PRIMARY KEY (ClientApplicationId),
	UNIQUE INDEX clientapplication_idx1 (ClientId) 
); 

INSERT IGNORE INTO clientapplication SET ClientApplicationId = 1, ClientId = '467402240984.apps.googleusercontent.com', BearerTokenProvider = 'Google', ApplicationName='Web App-project', ProjectName = 'API Project', EmailAddress = 'billhainaut@gmail.com', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplication SET ClientApplicationId = 2, ClientId = '4890422047764.apps.rheemapi.com', BearerTokenProvider = 'Rheem', ApplicationName='EcoNet Admin Test Driver', ProjectName = 'Rheem API', EmailAddress = 'billhainaut@gmail.com', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplication SET ClientApplicationId = 3, ClientId = '4890422047765.apps.rheemapi.com', BearerTokenProvider = 'Rheem', ApplicationName='EcoNet Phone App', ProjectName = 'Rheem API', EmailAddress = 'billhainaut@gmail.com', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplication SET ClientApplicationId = 4, ClientId = '4890422047766.apps.rheemapi.com', BearerTokenProvider = 'Rheem', ApplicationName='Rheem Web Partners', ProjectName = 'Rheem API', EmailAddress = 'billhainaut@gmail.com', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();

CREATE TABLE IF NOT EXISTS clientapplicationappdomain ( 
	ClientApplicationAppDomainId int(11) NOT NULL AUTO_INCREMENT, 
	ClientApplicationId int NOT NULL, 
	AppDomainId int NOT NULL, 
	CreateDateTime__Gen DATETIME NOT NULL, 
	UpdateDateTime__Gen DATETIME NOT NULL, 
	PRIMARY KEY (ClientApplicationAppDomainId), 
	Foreign Key(ClientApplicationId) references clientapplication(ClientApplicationId) on delete cascade, 
	Foreign Key(AppDomainId) references appdomain(AppDomainId) on delete cascade, 
	UNIQUE INDEX clientapplicationappdomain_idx1 (ClientApplicationId, AppDomainId) 
);

INSERT IGNORE INTO clientapplicationappdomain SET ClientApplicationAppDomainId = 1, ClientApplicationId = 2, AppDomainId = 1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplicationappdomain SET ClientApplicationAppDomainId = 2, ClientApplicationId = 2, AppDomainId = 2, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplicationappdomain SET ClientApplicationAppDomainId = 3, ClientApplicationId = 4, AppDomainId = 4, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO clientapplicationappdomain SET ClientApplicationAppDomainId = 4, ClientApplicationId = 3, AppDomainId = 1, UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();


 