/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertAPIMaster
   Get rid of obsolete UpdateAPIMaster
   Get rid of obsolete DeleteAPIMaster
   Get rid of obsolete SearchAPIMasterByString
   Get rid of obsolete GetAPIMasterByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertAPIMaster') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertAPIMaster;
        PRINT 'Dropped InsertAPIMaster'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateAPIMaster') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateAPIMaster;
        PRINT 'Dropped UpdateAPIMaster'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteAPIMaster') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteAPIMaster;
        PRINT 'Dropped DeleteAPIMaster'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchAPIMasterByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchAPIMasterByString;
        PRINT 'Dropped SearchAPIMasterByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetAPIMasterByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetAPIMasterByID;
        PRINT 'Dropped GetAPIMasterByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__APIMaster_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__APIMaster_GetByID;
        PRINT 'Dropped spGen__APIMaster_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__APIMaster_GetByID

   Description:  Selects record(s) from table 'APIMaster'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__APIMaster_GetByID
(
    @APIMasterID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [APIMasterID],[APIName],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [APIMaster]
    WHERE [APIMasterID] = @APIMasterID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__APIMaster_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__APIMaster_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__APIMaster_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__APIMaster_SearchByString;
        PRINT 'Dropped spGen__APIMaster_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__APIMaster_SearchByString

   Description:  Selects a record from table 'APIMaster'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__APIMaster_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [APIMasterID],[APIName],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [APIMaster]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__APIMaster_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__APIMaster_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__APIMaster_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__APIMaster_Delete;
        PRINT 'Dropped spGen__APIMaster_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__APIMaster_Delete

   Description:  Deletes a record from table 'APIMaster'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__APIMaster_Delete
(
    @APIMasterID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [APIMaster]
    WHERE [APIMasterID] = @APIMasterID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__APIMaster_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__APIMaster_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__APIMaster_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__APIMaster_Save;
        PRINT 'Dropped spGen__APIMaster_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__APIMaster_Save

   Description:  Updates or Deletes a record In table 'APIMaster'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__APIMaster_Save
(
    @ErrText varchar(4000) output,
    @APIMasterID uniqueidentifier output,
    @APIName varchar(50)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @APIMasterID = '00000000-0000-0000-0000-000000000000' SET @APIMasterID = NULL
    IF @APIMasterID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @APIMasterID = NewID()

                    INSERT
                    INTO [APIMaster]
                    (
                        [APIMasterID],
                        [APIName],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @APIMasterID,
                        @APIName,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [APIMaster]
                    SET
                    [APIName] = @APIName,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [APIMasterID] = @APIMasterID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__APIMaster_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__APIMaster_Save Error on Creation'
GO




