/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertCloudImageDefault
   Get rid of obsolete UpdateCloudImageDefault
   Get rid of obsolete DeleteCloudImageDefault
   Get rid of obsolete SearchCloudImageDefaultByString
   Get rid of obsolete GetCloudImageDefaultByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertCloudImageDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertCloudImageDefault;
        PRINT 'Dropped InsertCloudImageDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateCloudImageDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateCloudImageDefault;
        PRINT 'Dropped UpdateCloudImageDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteCloudImageDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteCloudImageDefault;
        PRINT 'Dropped DeleteCloudImageDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchCloudImageDefaultByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchCloudImageDefaultByString;
        PRINT 'Dropped SearchCloudImageDefaultByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetCloudImageDefaultByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetCloudImageDefaultByID;
        PRINT 'Dropped GetCloudImageDefaultByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__CloudImageDefault_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__CloudImageDefault_GetByID;
        PRINT 'Dropped spGen__CloudImageDefault_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__CloudImageDefault_GetByID

   Description:  Selects record(s) from table 'CloudImageDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__CloudImageDefault_GetByID
(
    @CloudImageDefaultID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [CloudImageDefaultID],[Height],[Width],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [CloudImageDefault]
    WHERE [CloudImageDefaultID] = @CloudImageDefaultID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__CloudImageDefault_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__CloudImageDefault_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__CloudImageDefault_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__CloudImageDefault_SearchByString;
        PRINT 'Dropped spGen__CloudImageDefault_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__CloudImageDefault_SearchByString

   Description:  Selects a record from table 'CloudImageDefault'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__CloudImageDefault_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [CloudImageDefaultID],[Height],[Width],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [CloudImageDefault]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__CloudImageDefault_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__CloudImageDefault_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__CloudImageDefault_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__CloudImageDefault_Delete;
        PRINT 'Dropped spGen__CloudImageDefault_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__CloudImageDefault_Delete

   Description:  Deletes a record from table 'CloudImageDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__CloudImageDefault_Delete
(
    @CloudImageDefaultID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [CloudImageDefault]
    WHERE [CloudImageDefaultID] = @CloudImageDefaultID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__CloudImageDefault_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__CloudImageDefault_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__CloudImageDefault_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__CloudImageDefault_Save;
        PRINT 'Dropped spGen__CloudImageDefault_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__CloudImageDefault_Save

   Description:  Updates or Deletes a record In table 'CloudImageDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__CloudImageDefault_Save
(
    @ErrText varchar(4000) output,
    @CloudImageDefaultID uniqueidentifier output,
    @Height int,
    @Width int
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @CloudImageDefaultID = '00000000-0000-0000-0000-000000000000' SET @CloudImageDefaultID = NULL
    IF @CloudImageDefaultID IS NULL
        BEGIN
            SELECT @UniqueRowCount = COUNT(1) FROM [CloudImageDefault] where [Height] = @Height and [Width] = @Width 
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = 'A row matching these unique index columns was found: Height, Width'
                END
            ELSE
                BEGIN
                    SET @CloudImageDefaultID = NewID()

                    INSERT
                    INTO [CloudImageDefault]
                    (
                        [CloudImageDefaultID],
                        [Height],
                        [Width],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @CloudImageDefaultID,
                        @Height,
                        @Width,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            -- check to see that there isn't another row like this one (assuming the unique index column(s) might have changed)
            SELECT @UniqueRowCount = COUNT(1) FROM [CloudImageDefault] where [Height] = @Height and [Width] = @Width  and [CloudImageDefaultID] <> @CloudImageDefaultID
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = 'A row matching these unique index columns was found: Height, Width'
                END
            ELSE
                BEGIN
                    UPDATE [CloudImageDefault]
                    SET
                    [Height] = @Height,
                    [Width] = @Width,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [CloudImageDefaultID] = @CloudImageDefaultID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__CloudImageDefault_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__CloudImageDefault_Save Error on Creation'
GO




