/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertContractorOrganization
   Get rid of obsolete UpdateContractorOrganization
   Get rid of obsolete DeleteContractorOrganization
   Get rid of obsolete SearchContractorOrganizationByString
   Get rid of obsolete GetContractorOrganizationByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertContractorOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertContractorOrganization;
        PRINT 'Dropped InsertContractorOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateContractorOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateContractorOrganization;
        PRINT 'Dropped UpdateContractorOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteContractorOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteContractorOrganization;
        PRINT 'Dropped DeleteContractorOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchContractorOrganizationByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchContractorOrganizationByString;
        PRINT 'Dropped SearchContractorOrganizationByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetContractorOrganizationByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetContractorOrganizationByID;
        PRINT 'Dropped GetContractorOrganizationByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganization_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganization_GetByID;
        PRINT 'Dropped spGen__ContractorOrganization_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganization_GetByID

   Description:  Selects record(s) from table 'ContractorOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganization_GetByID
(
    @ContractorOrganizationID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ContractorOrganizationID],[OrganizationID],[ACContractor],[WaterHeaterContractor],[PoolAndSpaContractor],[GeneratorContractor],[ServiceContractorDELETE],[Installer],[Disabled],[KwikComfort],[KwikComfortNumber],[CorporateEmail],[CountryID],[WebSite],[MarketID],[Radius],[FederalID],[BusinessType],[PrimaryAddressID],[FollowUp],[TAP],[RetailContractor],[ZipCodesUpdated],[FactoryDirectContractor],[ServiceExperts],[CreateDateTime__Gen],[UpdateDateTime__Gen],[TimeZone],[CustomerAccountID],[SiteUseID],[CorporateEmail2],[PHCC],[AboutUs]
    FROM [ContractorOrganization]
    WHERE [ContractorOrganizationID] = @ContractorOrganizationID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganization_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganization_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganization_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganization_SearchByString;
        PRINT 'Dropped spGen__ContractorOrganization_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganization_SearchByString

   Description:  Selects a record from table 'ContractorOrganization'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganization_SearchByString
(
    @searchParam varchar(8000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(8000)

    SET @strSql = ' Select [ContractorOrganizationID],[OrganizationID],[ACContractor],[WaterHeaterContractor],[PoolAndSpaContractor],[GeneratorContractor],[ServiceContractorDELETE],[Installer],[Disabled],[KwikComfort],[KwikComfortNumber],[CorporateEmail],[CountryID],[WebSite],[MarketID],[Radius],[FederalID],[BusinessType],[PrimaryAddressID],[FollowUp],[TAP],[RetailContractor],[ZipCodesUpdated],[FactoryDirectContractor],[ServiceExperts],[CreateDateTime__Gen],[UpdateDateTime__Gen],[TimeZone],[CustomerAccountID],[SiteUseID],[CorporateEmail2],[PHCC],[AboutUs]
    FROM [ContractorOrganization]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganization_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganization_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganization_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganization_Delete;
        PRINT 'Dropped spGen__ContractorOrganization_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganization_Delete

   Description:  Deletes a record from table 'ContractorOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganization_Delete
(
    @ContractorOrganizationID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ContractorOrganization]
    WHERE [ContractorOrganizationID] = @ContractorOrganizationID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganization_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganization_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganization_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganization_Save;
        PRINT 'Dropped spGen__ContractorOrganization_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganization_Save

   Description:  Updates or Deletes a record In table 'ContractorOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganization_Save
(
    @ErrText varchar(4000) output,
    @ContractorOrganizationID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @ACContractor bit,
    @WaterHeaterContractor bit,
    @PoolAndSpaContractor bit,
    @GeneratorContractor bit,
    @ServiceContractorDELETE bit,
    @Installer bit,
    @Disabled bit,
    @KwikComfort bit,
    @KwikComfortNumber varchar(50),
    @CorporateEmail varchar(50),
    @CountryID uniqueidentifier,
    @WebSite varchar(128),
    @MarketID uniqueidentifier,
    @Radius float,
    @FederalID varchar(50),
    @BusinessType char(1),
    @PrimaryAddressID uniqueidentifier,
    @FollowUp bit,
    @TAP bit,
    @RetailContractor bit,
    @ZipCodesUpdated datetime,
    @FactoryDirectContractor bit,
    @ServiceExperts bit,
    @TimeZone varchar(1),
    @CustomerAccountID varchar(50),
    @SiteUseID varchar(50),
    @CorporateEmail2 varchar(50),
    @PHCC bit,
    @AboutUs varchar(512)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ContractorOrganizationID = '00000000-0000-0000-0000-000000000000' SET @ContractorOrganizationID = NULL
    IF @ContractorOrganizationID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ContractorOrganizationID = NewID()

                    INSERT
                    INTO [ContractorOrganization]
                    (
                        [ContractorOrganizationID],
                        [OrganizationID],
                        [ACContractor],
                        [WaterHeaterContractor],
                        [PoolAndSpaContractor],
                        [GeneratorContractor],
                        [ServiceContractorDELETE],
                        [Installer],
                        [Disabled],
                        [KwikComfort],
                        [KwikComfortNumber],
                        [CorporateEmail],
                        [CountryID],
                        [WebSite],
                        [MarketID],
                        [Radius],
                        [FederalID],
                        [BusinessType],
                        [PrimaryAddressID],
                        [FollowUp],
                        [TAP],
                        [RetailContractor],
                        [ZipCodesUpdated],
                        [FactoryDirectContractor],
                        [ServiceExperts],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen],
                        [TimeZone],
                        [CustomerAccountID],
                        [SiteUseID],
                        [CorporateEmail2],
                        [PHCC],
                        [AboutUs]
                    )
                    VALUES
                    (
                        @ContractorOrganizationID,
                        @OrganizationID,
                        @ACContractor,
                        @WaterHeaterContractor,
                        @PoolAndSpaContractor,
                        @GeneratorContractor,
                        @ServiceContractorDELETE,
                        @Installer,
                        @Disabled,
                        @KwikComfort,
                        @KwikComfortNumber,
                        @CorporateEmail,
                        @CountryID,
                        @WebSite,
                        @MarketID,
                        @Radius,
                        @FederalID,
                        @BusinessType,
                        @PrimaryAddressID,
                        @FollowUp,
                        @TAP,
                        @RetailContractor,
                        @ZipCodesUpdated,
                        @FactoryDirectContractor,
                        @ServiceExperts,
                        SYSDATETIME(),
                        SYSDATETIME(),
                        @TimeZone,
                        @CustomerAccountID,
                        @SiteUseID,
                        @CorporateEmail2,
                        @PHCC,
                        @AboutUs
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ContractorOrganization]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [ACContractor] = @ACContractor,
                    [WaterHeaterContractor] = @WaterHeaterContractor,
                    [PoolAndSpaContractor] = @PoolAndSpaContractor,
                    [GeneratorContractor] = @GeneratorContractor,
                    [ServiceContractorDELETE] = @ServiceContractorDELETE,
                    [Installer] = @Installer,
                    [Disabled] = @Disabled,
                    [KwikComfort] = @KwikComfort,
                    [KwikComfortNumber] = @KwikComfortNumber,
                    [CorporateEmail] = @CorporateEmail,
                    [CountryID] = @CountryID,
                    [WebSite] = @WebSite,
                    [MarketID] = @MarketID,
                    [Radius] = @Radius,
                    [FederalID] = @FederalID,
                    [BusinessType] = @BusinessType,
                    [PrimaryAddressID] = @PrimaryAddressID,
                    [FollowUp] = @FollowUp,
                    [TAP] = @TAP,
                    [RetailContractor] = @RetailContractor,
                    [ZipCodesUpdated] = @ZipCodesUpdated,
                    [FactoryDirectContractor] = @FactoryDirectContractor,
                    [ServiceExperts] = @ServiceExperts,
                    [UpdateDateTime__Gen] = SYSDATETIME(),
                    [TimeZone] = @TimeZone,
                    [CustomerAccountID] = @CustomerAccountID,
                    [SiteUseID] = @SiteUseID,
                    [CorporateEmail2] = @CorporateEmail2,
                    [PHCC] = @PHCC,
                    [AboutUs] = @AboutUs
                    WHERE [ContractorOrganizationID] = @ContractorOrganizationID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganization_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganization_Save Error on Creation'
GO




