/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertContractorRetail
   Get rid of obsolete UpdateContractorRetail
   Get rid of obsolete DeleteContractorRetail
   Get rid of obsolete SearchContractorRetailByString
   Get rid of obsolete GetContractorRetailByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertContractorRetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertContractorRetail;
        PRINT 'Dropped InsertContractorRetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateContractorRetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateContractorRetail;
        PRINT 'Dropped UpdateContractorRetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteContractorRetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteContractorRetail;
        PRINT 'Dropped DeleteContractorRetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchContractorRetailByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchContractorRetailByString;
        PRINT 'Dropped SearchContractorRetailByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetContractorRetailByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetContractorRetailByID;
        PRINT 'Dropped GetContractorRetailByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorRetail_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorRetail_GetByID;
        PRINT 'Dropped spGen__ContractorRetail_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorRetail_GetByID

   Description:  Selects record(s) from table 'ContractorRetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorRetail_GetByID
(
    @ContractorRetailID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ContractorRetailID],[OrganizationID],[HomeDepot],[HDVendorNumber],[Contact],[Disabled],[HDCashback],[PersonCreated],[LiteratureBundleCount],[VendorNumber],[HDShowOnLocator],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorRetail]
    WHERE [ContractorRetailID] = @ContractorRetailID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorRetail_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorRetail_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorRetail_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorRetail_SearchByString;
        PRINT 'Dropped spGen__ContractorRetail_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorRetail_SearchByString

   Description:  Selects a record from table 'ContractorRetail'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorRetail_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ContractorRetailID],[OrganizationID],[HomeDepot],[HDVendorNumber],[Contact],[Disabled],[HDCashback],[PersonCreated],[LiteratureBundleCount],[VendorNumber],[HDShowOnLocator],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorRetail]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorRetail_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorRetail_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorRetail_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorRetail_Delete;
        PRINT 'Dropped spGen__ContractorRetail_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorRetail_Delete

   Description:  Deletes a record from table 'ContractorRetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorRetail_Delete
(
    @ContractorRetailID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ContractorRetail]
    WHERE [ContractorRetailID] = @ContractorRetailID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorRetail_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorRetail_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorRetail_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorRetail_Save;
        PRINT 'Dropped spGen__ContractorRetail_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorRetail_Save

   Description:  Updates or Deletes a record In table 'ContractorRetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorRetail_Save
(
    @ErrText varchar(4000) output,
    @ContractorRetailID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @HomeDepot bit,
    @HDVendorNumber int,
    @Contact varchar(50),
    @Disabled bit,
    @HDCashback bit,
    @PersonCreated datetime,
    @LiteratureBundleCount int,
    @VendorNumber int,
    @HDShowOnLocator bit
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ContractorRetailID = '00000000-0000-0000-0000-000000000000' SET @ContractorRetailID = NULL
    IF @ContractorRetailID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ContractorRetailID = NewID()

                    INSERT
                    INTO [ContractorRetail]
                    (
                        [ContractorRetailID],
                        [OrganizationID],
                        [HomeDepot],
                        [HDVendorNumber],
                        [Contact],
                        [Disabled],
                        [HDCashback],
                        [PersonCreated],
                        [LiteratureBundleCount],
                        [VendorNumber],
                        [HDShowOnLocator],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ContractorRetailID,
                        @OrganizationID,
                        @HomeDepot,
                        @HDVendorNumber,
                        @Contact,
                        @Disabled,
                        @HDCashback,
                        @PersonCreated,
                        @LiteratureBundleCount,
                        @VendorNumber,
                        @HDShowOnLocator,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ContractorRetail]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [HomeDepot] = @HomeDepot,
                    [HDVendorNumber] = @HDVendorNumber,
                    [Contact] = @Contact,
                    [Disabled] = @Disabled,
                    [HDCashback] = @HDCashback,
                    [PersonCreated] = @PersonCreated,
                    [LiteratureBundleCount] = @LiteratureBundleCount,
                    [VendorNumber] = @VendorNumber,
                    [HDShowOnLocator] = @HDShowOnLocator,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ContractorRetailID] = @ContractorRetailID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorRetail_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorRetail_Save Error on Creation'
GO




