/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertContractorOrganizationRanking
   Get rid of obsolete UpdateContractorOrganizationRanking
   Get rid of obsolete DeleteContractorOrganizationRanking
   Get rid of obsolete SearchContractorOrganizationRankingByString
   Get rid of obsolete GetContractorOrganizationRankingByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertContractorOrganizationRanking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertContractorOrganizationRanking;
        PRINT 'Dropped InsertContractorOrganizationRanking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateContractorOrganizationRanking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateContractorOrganizationRanking;
        PRINT 'Dropped UpdateContractorOrganizationRanking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteContractorOrganizationRanking') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteContractorOrganizationRanking;
        PRINT 'Dropped DeleteContractorOrganizationRanking'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchContractorOrganizationRankingByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchContractorOrganizationRankingByString;
        PRINT 'Dropped SearchContractorOrganizationRankingByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetContractorOrganizationRankingByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetContractorOrganizationRankingByID;
        PRINT 'Dropped GetContractorOrganizationRankingByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganizationRanking_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganizationRanking_GetByID;
        PRINT 'Dropped spGen__ContractorOrganizationRanking_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganizationRanking_GetByID

   Description:  Selects record(s) from table 'ContractorOrganizationRanking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganizationRanking_GetByID
(
    @ContractorOrganizationRankingID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ContractorOrganizationRankingID],[ContractorWaterHeaterID],[RatingCriteriaID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorOrganizationRanking]
    WHERE [ContractorOrganizationRankingID] = @ContractorOrganizationRankingID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganizationRanking_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganizationRanking_SearchByString;
        PRINT 'Dropped spGen__ContractorOrganizationRanking_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganizationRanking_SearchByString

   Description:  Selects a record from table 'ContractorOrganizationRanking'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganizationRanking_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ContractorOrganizationRankingID],[ContractorWaterHeaterID],[RatingCriteriaID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorOrganizationRanking]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganizationRanking_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganizationRanking_Delete;
        PRINT 'Dropped spGen__ContractorOrganizationRanking_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganizationRanking_Delete

   Description:  Deletes a record from table 'ContractorOrganizationRanking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganizationRanking_Delete
(
    @ContractorOrganizationRankingID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ContractorOrganizationRanking]
    WHERE [ContractorOrganizationRankingID] = @ContractorOrganizationRankingID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorOrganizationRanking_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorOrganizationRanking_Save;
        PRINT 'Dropped spGen__ContractorOrganizationRanking_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorOrganizationRanking_Save

   Description:  Updates or Deletes a record In table 'ContractorOrganizationRanking'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorOrganizationRanking_Save
(
    @ErrText varchar(4000) output,
    @ContractorOrganizationRankingID uniqueidentifier output,
    @ContractorWaterHeaterID uniqueidentifier,
    @RatingCriteriaID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ContractorOrganizationRankingID = '00000000-0000-0000-0000-000000000000' SET @ContractorOrganizationRankingID = NULL
    IF @ContractorOrganizationRankingID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ContractorOrganizationRankingID = NewID()

                    INSERT
                    INTO [ContractorOrganizationRanking]
                    (
                        [ContractorOrganizationRankingID],
                        [ContractorWaterHeaterID],
                        [RatingCriteriaID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ContractorOrganizationRankingID,
                        @ContractorWaterHeaterID,
                        @RatingCriteriaID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ContractorOrganizationRanking]
                    SET
                    [ContractorWaterHeaterID] = @ContractorWaterHeaterID,
                    [RatingCriteriaID] = @RatingCriteriaID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ContractorOrganizationRankingID] = @ContractorOrganizationRankingID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorOrganizationRanking_Save Error on Creation'
GO




