/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertContractorWSKeywordReferences
   Get rid of obsolete UpdateContractorWSKeywordReferences
   Get rid of obsolete DeleteContractorWSKeywordReferences
   Get rid of obsolete SearchContractorWSKeywordReferencesByString
   Get rid of obsolete GetContractorWSKeywordReferencesByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertContractorWSKeywordReferences') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertContractorWSKeywordReferences;
        PRINT 'Dropped InsertContractorWSKeywordReferences'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateContractorWSKeywordReferences') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateContractorWSKeywordReferences;
        PRINT 'Dropped UpdateContractorWSKeywordReferences'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteContractorWSKeywordReferences') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteContractorWSKeywordReferences;
        PRINT 'Dropped DeleteContractorWSKeywordReferences'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchContractorWSKeywordReferencesByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchContractorWSKeywordReferencesByString;
        PRINT 'Dropped SearchContractorWSKeywordReferencesByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetContractorWSKeywordReferencesByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetContractorWSKeywordReferencesByID;
        PRINT 'Dropped GetContractorWSKeywordReferencesByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorWSKeywordReferences_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorWSKeywordReferences_GetByID;
        PRINT 'Dropped spGen__ContractorWSKeywordReferences_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorWSKeywordReferences_GetByID

   Description:  Selects record(s) from table 'ContractorWSKeywordReferences'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorWSKeywordReferences_GetByID
(
    @KeywordReferencesID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [KeywordReferencesID],[ContractorWSPageID],[Keyword],[ReferenceCount],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorWSKeywordReferences]
    WHERE [KeywordReferencesID] = @KeywordReferencesID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorWSKeywordReferences_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorWSKeywordReferences_SearchByString;
        PRINT 'Dropped spGen__ContractorWSKeywordReferences_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorWSKeywordReferences_SearchByString

   Description:  Selects a record from table 'ContractorWSKeywordReferences'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorWSKeywordReferences_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [KeywordReferencesID],[ContractorWSPageID],[Keyword],[ReferenceCount],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorWSKeywordReferences]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorWSKeywordReferences_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorWSKeywordReferences_Delete;
        PRINT 'Dropped spGen__ContractorWSKeywordReferences_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorWSKeywordReferences_Delete

   Description:  Deletes a record from table 'ContractorWSKeywordReferences'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorWSKeywordReferences_Delete
(
    @KeywordReferencesID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ContractorWSKeywordReferences]
    WHERE [KeywordReferencesID] = @KeywordReferencesID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorWSKeywordReferences_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorWSKeywordReferences_Save;
        PRINT 'Dropped spGen__ContractorWSKeywordReferences_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorWSKeywordReferences_Save

   Description:  Updates or Deletes a record In table 'ContractorWSKeywordReferences'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorWSKeywordReferences_Save
(
    @ErrText varchar(4000) output,
    @KeywordReferencesID uniqueidentifier output,
    @ContractorWSPageID uniqueidentifier,
    @Keyword varchar(128),
    @ReferenceCount int
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @KeywordReferencesID = '00000000-0000-0000-0000-000000000000' SET @KeywordReferencesID = NULL
    IF @KeywordReferencesID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @KeywordReferencesID = NewID()

                    INSERT
                    INTO [ContractorWSKeywordReferences]
                    (
                        [KeywordReferencesID],
                        [ContractorWSPageID],
                        [Keyword],
                        [ReferenceCount],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @KeywordReferencesID,
                        @ContractorWSPageID,
                        @Keyword,
                        @ReferenceCount,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ContractorWSKeywordReferences]
                    SET
                    [ContractorWSPageID] = @ContractorWSPageID,
                    [Keyword] = @Keyword,
                    [ReferenceCount] = @ReferenceCount,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [KeywordReferencesID] = @KeywordReferencesID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorWSKeywordReferences_Save Error on Creation'
GO




