/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertContractorLeadsBrands
   Get rid of obsolete UpdateContractorLeadsBrands
   Get rid of obsolete DeleteContractorLeadsBrands
   Get rid of obsolete SearchContractorLeadsBrandsByString
   Get rid of obsolete GetContractorLeadsBrandsByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertContractorLeadsBrands') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertContractorLeadsBrands;
        PRINT 'Dropped InsertContractorLeadsBrands'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateContractorLeadsBrands') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateContractorLeadsBrands;
        PRINT 'Dropped UpdateContractorLeadsBrands'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteContractorLeadsBrands') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteContractorLeadsBrands;
        PRINT 'Dropped DeleteContractorLeadsBrands'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchContractorLeadsBrandsByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchContractorLeadsBrandsByString;
        PRINT 'Dropped SearchContractorLeadsBrandsByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetContractorLeadsBrandsByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetContractorLeadsBrandsByID;
        PRINT 'Dropped GetContractorLeadsBrandsByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorLeadsBrands_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorLeadsBrands_GetByID;
        PRINT 'Dropped spGen__ContractorLeadsBrands_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorLeadsBrands_GetByID

   Description:  Selects record(s) from table 'ContractorLeadsBrands'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorLeadsBrands_GetByID
(
    @ContractorLeadsBrandID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ContractorLeadsBrandID],[ContractorLeadsID],[BrandCompetitorID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorLeadsBrands]
    WHERE [ContractorLeadsBrandID] = @ContractorLeadsBrandID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorLeadsBrands_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorLeadsBrands_SearchByString;
        PRINT 'Dropped spGen__ContractorLeadsBrands_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorLeadsBrands_SearchByString

   Description:  Selects a record from table 'ContractorLeadsBrands'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorLeadsBrands_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ContractorLeadsBrandID],[ContractorLeadsID],[BrandCompetitorID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ContractorLeadsBrands]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorLeadsBrands_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorLeadsBrands_Delete;
        PRINT 'Dropped spGen__ContractorLeadsBrands_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorLeadsBrands_Delete

   Description:  Deletes a record from table 'ContractorLeadsBrands'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorLeadsBrands_Delete
(
    @ContractorLeadsBrandID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ContractorLeadsBrands]
    WHERE [ContractorLeadsBrandID] = @ContractorLeadsBrandID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ContractorLeadsBrands_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ContractorLeadsBrands_Save;
        PRINT 'Dropped spGen__ContractorLeadsBrands_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ContractorLeadsBrands_Save

   Description:  Updates or Deletes a record In table 'ContractorLeadsBrands'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ContractorLeadsBrands_Save
(
    @ErrText varchar(4000) output,
    @ContractorLeadsBrandID uniqueidentifier output,
    @ContractorLeadsID uniqueidentifier,
    @BrandCompetitorID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ContractorLeadsBrandID = '00000000-0000-0000-0000-000000000000' SET @ContractorLeadsBrandID = NULL
    IF @ContractorLeadsBrandID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ContractorLeadsBrandID = NewID()

                    INSERT
                    INTO [ContractorLeadsBrands]
                    (
                        [ContractorLeadsBrandID],
                        [ContractorLeadsID],
                        [BrandCompetitorID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ContractorLeadsBrandID,
                        @ContractorLeadsID,
                        @BrandCompetitorID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ContractorLeadsBrands]
                    SET
                    [ContractorLeadsID] = @ContractorLeadsID,
                    [BrandCompetitorID] = @BrandCompetitorID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ContractorLeadsBrandID] = @ContractorLeadsBrandID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ContractorLeadsBrands_Save Error on Creation'
GO




