/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertFactoryDirectOrganizations
   Get rid of obsolete UpdateFactoryDirectOrganizations
   Get rid of obsolete DeleteFactoryDirectOrganizations
   Get rid of obsolete SearchFactoryDirectOrganizationsByString
   Get rid of obsolete GetFactoryDirectOrganizationsByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertFactoryDirectOrganizations') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertFactoryDirectOrganizations;
        PRINT 'Dropped InsertFactoryDirectOrganizations'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateFactoryDirectOrganizations') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateFactoryDirectOrganizations;
        PRINT 'Dropped UpdateFactoryDirectOrganizations'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteFactoryDirectOrganizations') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteFactoryDirectOrganizations;
        PRINT 'Dropped DeleteFactoryDirectOrganizations'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchFactoryDirectOrganizationsByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchFactoryDirectOrganizationsByString;
        PRINT 'Dropped SearchFactoryDirectOrganizationsByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetFactoryDirectOrganizationsByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetFactoryDirectOrganizationsByID;
        PRINT 'Dropped GetFactoryDirectOrganizationsByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__FactoryDirectOrganizations_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__FactoryDirectOrganizations_GetByID;
        PRINT 'Dropped spGen__FactoryDirectOrganizations_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__FactoryDirectOrganizations_GetByID

   Description:  Selects record(s) from table 'FactoryDirectOrganizations'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__FactoryDirectOrganizations_GetByID
(
    @FactoryDirectOrganizationID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [FactoryDirectOrganizationID],[OrganizationID],[PrimaryAddressID],[SureComfort],[SureComfortNumber],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [FactoryDirectOrganizations]
    WHERE [FactoryDirectOrganizationID] = @FactoryDirectOrganizationID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__FactoryDirectOrganizations_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__FactoryDirectOrganizations_SearchByString;
        PRINT 'Dropped spGen__FactoryDirectOrganizations_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__FactoryDirectOrganizations_SearchByString

   Description:  Selects a record from table 'FactoryDirectOrganizations'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__FactoryDirectOrganizations_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [FactoryDirectOrganizationID],[OrganizationID],[PrimaryAddressID],[SureComfort],[SureComfortNumber],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [FactoryDirectOrganizations]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__FactoryDirectOrganizations_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__FactoryDirectOrganizations_Delete;
        PRINT 'Dropped spGen__FactoryDirectOrganizations_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__FactoryDirectOrganizations_Delete

   Description:  Deletes a record from table 'FactoryDirectOrganizations'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__FactoryDirectOrganizations_Delete
(
    @FactoryDirectOrganizationID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [FactoryDirectOrganizations]
    WHERE [FactoryDirectOrganizationID] = @FactoryDirectOrganizationID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__FactoryDirectOrganizations_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__FactoryDirectOrganizations_Save;
        PRINT 'Dropped spGen__FactoryDirectOrganizations_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__FactoryDirectOrganizations_Save

   Description:  Updates or Deletes a record In table 'FactoryDirectOrganizations'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__FactoryDirectOrganizations_Save
(
    @ErrText varchar(4000) output,
    @FactoryDirectOrganizationID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @PrimaryAddressID uniqueidentifier,
    @SureComfort bit,
    @SureComfortNumber int
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @FactoryDirectOrganizationID = '00000000-0000-0000-0000-000000000000' SET @FactoryDirectOrganizationID = NULL
    IF @FactoryDirectOrganizationID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @FactoryDirectOrganizationID = NewID()

                    INSERT
                    INTO [FactoryDirectOrganizations]
                    (
                        [FactoryDirectOrganizationID],
                        [OrganizationID],
                        [PrimaryAddressID],
                        [SureComfort],
                        [SureComfortNumber],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @FactoryDirectOrganizationID,
                        @OrganizationID,
                        @PrimaryAddressID,
                        @SureComfort,
                        @SureComfortNumber,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [FactoryDirectOrganizations]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [PrimaryAddressID] = @PrimaryAddressID,
                    [SureComfort] = @SureComfort,
                    [SureComfortNumber] = @SureComfortNumber,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [FactoryDirectOrganizationID] = @FactoryDirectOrganizationID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__FactoryDirectOrganizations_Save Error on Creation'
GO




