/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertHDOptionDefault
   Get rid of obsolete UpdateHDOptionDefault
   Get rid of obsolete DeleteHDOptionDefault
   Get rid of obsolete SearchHDOptionDefaultByString
   Get rid of obsolete GetHDOptionDefaultByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertHDOptionDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertHDOptionDefault;
        PRINT 'Dropped InsertHDOptionDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateHDOptionDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateHDOptionDefault;
        PRINT 'Dropped UpdateHDOptionDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteHDOptionDefault') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteHDOptionDefault;
        PRINT 'Dropped DeleteHDOptionDefault'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchHDOptionDefaultByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchHDOptionDefaultByString;
        PRINT 'Dropped SearchHDOptionDefaultByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetHDOptionDefaultByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetHDOptionDefaultByID;
        PRINT 'Dropped GetHDOptionDefaultByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDOptionDefault_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDOptionDefault_GetByID;
        PRINT 'Dropped spGen__HDOptionDefault_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDOptionDefault_GetByID

   Description:  Selects record(s) from table 'HDOptionDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDOptionDefault_GetByID
(
    @HDOptionDefaultID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [HDOptionDefaultID],[HDOptionDefaultPersonID],[HDOptionDefaultOrganizationID],[HDOptionDefaultType],[ScopeOfWork],[Option1Details],[Option2Details],[Option3Details],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [HDOptionDefault]
    WHERE [HDOptionDefaultID] = @HDOptionDefaultID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDOptionDefault_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__HDOptionDefault_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDOptionDefault_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDOptionDefault_SearchByString;
        PRINT 'Dropped spGen__HDOptionDefault_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDOptionDefault_SearchByString

   Description:  Selects a record from table 'HDOptionDefault'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDOptionDefault_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [HDOptionDefaultID],[HDOptionDefaultPersonID],[HDOptionDefaultOrganizationID],[HDOptionDefaultType],[ScopeOfWork],[Option1Details],[Option2Details],[Option3Details],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [HDOptionDefault]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDOptionDefault_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__HDOptionDefault_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDOptionDefault_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDOptionDefault_Delete;
        PRINT 'Dropped spGen__HDOptionDefault_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDOptionDefault_Delete

   Description:  Deletes a record from table 'HDOptionDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDOptionDefault_Delete
(
    @HDOptionDefaultID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [HDOptionDefault]
    WHERE [HDOptionDefaultID] = @HDOptionDefaultID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDOptionDefault_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__HDOptionDefault_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDOptionDefault_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDOptionDefault_Save;
        PRINT 'Dropped spGen__HDOptionDefault_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDOptionDefault_Save

   Description:  Updates or Deletes a record In table 'HDOptionDefault'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDOptionDefault_Save
(
    @ErrText varchar(4000) output,
    @HDOptionDefaultID uniqueidentifier output,
    @HDOptionDefaultPersonID uniqueidentifier,
    @HDOptionDefaultOrganizationID uniqueidentifier,
    @HDOptionDefaultType varchar(50),
    @ScopeOfWork ntext,
    @Option1Details ntext,
    @Option2Details ntext,
    @Option3Details ntext
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @HDOptionDefaultID = '00000000-0000-0000-0000-000000000000' SET @HDOptionDefaultID = NULL
    IF @HDOptionDefaultID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @HDOptionDefaultID = NewID()

                    INSERT
                    INTO [HDOptionDefault]
                    (
                        [HDOptionDefaultID],
                        [HDOptionDefaultPersonID],
                        [HDOptionDefaultOrganizationID],
                        [HDOptionDefaultType],
                        [ScopeOfWork],
                        [Option1Details],
                        [Option2Details],
                        [Option3Details],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @HDOptionDefaultID,
                        @HDOptionDefaultPersonID,
                        @HDOptionDefaultOrganizationID,
                        @HDOptionDefaultType,
                        @ScopeOfWork,
                        @Option1Details,
                        @Option2Details,
                        @Option3Details,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [HDOptionDefault]
                    SET
                    [HDOptionDefaultPersonID] = @HDOptionDefaultPersonID,
                    [HDOptionDefaultOrganizationID] = @HDOptionDefaultOrganizationID,
                    [HDOptionDefaultType] = @HDOptionDefaultType,
                    [ScopeOfWork] = @ScopeOfWork,
                    [Option1Details] = @Option1Details,
                    [Option2Details] = @Option2Details,
                    [Option3Details] = @Option3Details,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [HDOptionDefaultID] = @HDOptionDefaultID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDOptionDefault_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__HDOptionDefault_Save Error on Creation'
GO




