/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertHDPersonToPersonAccess
   Get rid of obsolete UpdateHDPersonToPersonAccess
   Get rid of obsolete DeleteHDPersonToPersonAccess
   Get rid of obsolete SearchHDPersonToPersonAccessByString
   Get rid of obsolete GetHDPersonToPersonAccessByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertHDPersonToPersonAccess') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertHDPersonToPersonAccess;
        PRINT 'Dropped InsertHDPersonToPersonAccess'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateHDPersonToPersonAccess') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateHDPersonToPersonAccess;
        PRINT 'Dropped UpdateHDPersonToPersonAccess'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteHDPersonToPersonAccess') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteHDPersonToPersonAccess;
        PRINT 'Dropped DeleteHDPersonToPersonAccess'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchHDPersonToPersonAccessByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchHDPersonToPersonAccessByString;
        PRINT 'Dropped SearchHDPersonToPersonAccessByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetHDPersonToPersonAccessByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetHDPersonToPersonAccessByID;
        PRINT 'Dropped GetHDPersonToPersonAccessByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDPersonToPersonAccess_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDPersonToPersonAccess_GetByID;
        PRINT 'Dropped spGen__HDPersonToPersonAccess_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDPersonToPersonAccess_GetByID

   Description:  Selects record(s) from table 'HDPersonToPersonAccess'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDPersonToPersonAccess_GetByID
(
    @HDPersonToPersonAccessID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [HDPersonToPersonAccessID],[PersonID],[HasAccessToPersonID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [HDPersonToPersonAccess]
    WHERE [HDPersonToPersonAccessID] = @HDPersonToPersonAccessID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDPersonToPersonAccess_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDPersonToPersonAccess_SearchByString;
        PRINT 'Dropped spGen__HDPersonToPersonAccess_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDPersonToPersonAccess_SearchByString

   Description:  Selects a record from table 'HDPersonToPersonAccess'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDPersonToPersonAccess_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [HDPersonToPersonAccessID],[PersonID],[HasAccessToPersonID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [HDPersonToPersonAccess]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDPersonToPersonAccess_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDPersonToPersonAccess_Delete;
        PRINT 'Dropped spGen__HDPersonToPersonAccess_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDPersonToPersonAccess_Delete

   Description:  Deletes a record from table 'HDPersonToPersonAccess'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDPersonToPersonAccess_Delete
(
    @HDPersonToPersonAccessID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [HDPersonToPersonAccess]
    WHERE [HDPersonToPersonAccessID] = @HDPersonToPersonAccessID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__HDPersonToPersonAccess_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__HDPersonToPersonAccess_Save;
        PRINT 'Dropped spGen__HDPersonToPersonAccess_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__HDPersonToPersonAccess_Save

   Description:  Updates or Deletes a record In table 'HDPersonToPersonAccess'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__HDPersonToPersonAccess_Save
(
    @ErrText varchar(4000) output,
    @HDPersonToPersonAccessID uniqueidentifier output,
    @PersonID uniqueidentifier,
    @HasAccessToPersonID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @HDPersonToPersonAccessID = '00000000-0000-0000-0000-000000000000' SET @HDPersonToPersonAccessID = NULL
    IF @HDPersonToPersonAccessID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @HDPersonToPersonAccessID = NewID()

                    INSERT
                    INTO [HDPersonToPersonAccess]
                    (
                        [HDPersonToPersonAccessID],
                        [PersonID],
                        [HasAccessToPersonID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @HDPersonToPersonAccessID,
                        @PersonID,
                        @HasAccessToPersonID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [HDPersonToPersonAccess]
                    SET
                    [PersonID] = @PersonID,
                    [HasAccessToPersonID] = @HasAccessToPersonID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [HDPersonToPersonAccessID] = @HDPersonToPersonAccessID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__HDPersonToPersonAccess_Save Error on Creation'
GO




