/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertListUserList
   Get rid of obsolete UpdateListUserList
   Get rid of obsolete DeleteListUserList
   Get rid of obsolete SearchListUserListByString
   Get rid of obsolete GetListUserListByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertListUserList') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertListUserList;
        PRINT 'Dropped InsertListUserList'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateListUserList') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateListUserList;
        PRINT 'Dropped UpdateListUserList'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteListUserList') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteListUserList;
        PRINT 'Dropped DeleteListUserList'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchListUserListByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchListUserListByString;
        PRINT 'Dropped SearchListUserListByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetListUserListByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetListUserListByID;
        PRINT 'Dropped GetListUserListByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ListUserList_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ListUserList_GetByID;
        PRINT 'Dropped spGen__ListUserList_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ListUserList_GetByID

   Description:  Selects record(s) from table 'ListUserList'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ListUserList_GetByID
(
    @ListUserListID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ListUserListID],[ListID],[PersonID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ListUserList]
    WHERE [ListUserListID] = @ListUserListID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ListUserList_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ListUserList_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ListUserList_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ListUserList_SearchByString;
        PRINT 'Dropped spGen__ListUserList_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ListUserList_SearchByString

   Description:  Selects a record from table 'ListUserList'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ListUserList_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ListUserListID],[ListID],[PersonID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ListUserList]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ListUserList_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ListUserList_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ListUserList_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ListUserList_Delete;
        PRINT 'Dropped spGen__ListUserList_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ListUserList_Delete

   Description:  Deletes a record from table 'ListUserList'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ListUserList_Delete
(
    @ListUserListID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ListUserList]
    WHERE [ListUserListID] = @ListUserListID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ListUserList_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ListUserList_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ListUserList_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ListUserList_Save;
        PRINT 'Dropped spGen__ListUserList_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ListUserList_Save

   Description:  Updates or Deletes a record In table 'ListUserList'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ListUserList_Save
(
    @ErrText varchar(4000) output,
    @ListUserListID uniqueidentifier output,
    @ListID uniqueidentifier,
    @PersonID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ListUserListID = '00000000-0000-0000-0000-000000000000' SET @ListUserListID = NULL
    IF @ListUserListID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ListUserListID = NewID()

                    INSERT
                    INTO [ListUserList]
                    (
                        [ListUserListID],
                        [ListID],
                        [PersonID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ListUserListID,
                        @ListID,
                        @PersonID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ListUserList]
                    SET
                    [ListID] = @ListID,
                    [PersonID] = @PersonID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ListUserListID] = @ListUserListID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ListUserList_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ListUserList_Save Error on Creation'
GO




