/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertOrganizationBrand
   Get rid of obsolete UpdateOrganizationBrand
   Get rid of obsolete DeleteOrganizationBrand
   Get rid of obsolete SearchOrganizationBrandByString
   Get rid of obsolete GetOrganizationBrandByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertOrganizationBrand') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertOrganizationBrand;
        PRINT 'Dropped InsertOrganizationBrand'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateOrganizationBrand') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateOrganizationBrand;
        PRINT 'Dropped UpdateOrganizationBrand'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteOrganizationBrand') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteOrganizationBrand;
        PRINT 'Dropped DeleteOrganizationBrand'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchOrganizationBrandByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchOrganizationBrandByString;
        PRINT 'Dropped SearchOrganizationBrandByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetOrganizationBrandByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetOrganizationBrandByID;
        PRINT 'Dropped GetOrganizationBrandByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__OrganizationBrand_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__OrganizationBrand_GetByID;
        PRINT 'Dropped spGen__OrganizationBrand_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__OrganizationBrand_GetByID

   Description:  Selects record(s) from table 'OrganizationBrand'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__OrganizationBrand_GetByID
(
    @OrganizationBrandID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [OrganizationBrandID],[OrganizationID],[BrandID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [OrganizationBrand]
    WHERE [OrganizationBrandID] = @OrganizationBrandID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__OrganizationBrand_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__OrganizationBrand_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__OrganizationBrand_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__OrganizationBrand_SearchByString;
        PRINT 'Dropped spGen__OrganizationBrand_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__OrganizationBrand_SearchByString

   Description:  Selects a record from table 'OrganizationBrand'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__OrganizationBrand_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [OrganizationBrandID],[OrganizationID],[BrandID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [OrganizationBrand]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__OrganizationBrand_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__OrganizationBrand_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__OrganizationBrand_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__OrganizationBrand_Delete;
        PRINT 'Dropped spGen__OrganizationBrand_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__OrganizationBrand_Delete

   Description:  Deletes a record from table 'OrganizationBrand'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__OrganizationBrand_Delete
(
    @OrganizationBrandID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [OrganizationBrand]
    WHERE [OrganizationBrandID] = @OrganizationBrandID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__OrganizationBrand_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__OrganizationBrand_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__OrganizationBrand_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__OrganizationBrand_Save;
        PRINT 'Dropped spGen__OrganizationBrand_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__OrganizationBrand_Save

   Description:  Updates or Deletes a record In table 'OrganizationBrand'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__OrganizationBrand_Save
(
    @ErrText varchar(4000) output,
    @OrganizationBrandID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @BrandID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @OrganizationBrandID = '00000000-0000-0000-0000-000000000000' SET @OrganizationBrandID = NULL
    IF @OrganizationBrandID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @OrganizationBrandID = NewID()

                    INSERT
                    INTO [OrganizationBrand]
                    (
                        [OrganizationBrandID],
                        [OrganizationID],
                        [BrandID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @OrganizationBrandID,
                        @OrganizationID,
                        @BrandID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [OrganizationBrand]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [BrandID] = @BrandID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [OrganizationBrandID] = @OrganizationBrandID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__OrganizationBrand_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__OrganizationBrand_Save Error on Creation'
GO




