/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertPendingRoleRequest
   Get rid of obsolete UpdatePendingRoleRequest
   Get rid of obsolete DeletePendingRoleRequest
   Get rid of obsolete SearchPendingRoleRequestByString
   Get rid of obsolete GetPendingRoleRequestByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertPendingRoleRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertPendingRoleRequest;
        PRINT 'Dropped InsertPendingRoleRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdatePendingRoleRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdatePendingRoleRequest;
        PRINT 'Dropped UpdatePendingRoleRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeletePendingRoleRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeletePendingRoleRequest;
        PRINT 'Dropped DeletePendingRoleRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchPendingRoleRequestByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchPendingRoleRequestByString;
        PRINT 'Dropped SearchPendingRoleRequestByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetPendingRoleRequestByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetPendingRoleRequestByID;
        PRINT 'Dropped GetPendingRoleRequestByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PendingRoleRequest_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PendingRoleRequest_GetByID;
        PRINT 'Dropped spGen__PendingRoleRequest_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PendingRoleRequest_GetByID

   Description:  Selects record(s) from table 'PendingRoleRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PendingRoleRequest_GetByID
(
    @PendingRoleRequestID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [PendingRoleRequestID],[PersonID],[ApplicationRoleID],[RequestDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [PendingRoleRequest]
    WHERE [PendingRoleRequestID] = @PendingRoleRequestID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PendingRoleRequest_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__PendingRoleRequest_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PendingRoleRequest_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PendingRoleRequest_SearchByString;
        PRINT 'Dropped spGen__PendingRoleRequest_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PendingRoleRequest_SearchByString

   Description:  Selects a record from table 'PendingRoleRequest'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PendingRoleRequest_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [PendingRoleRequestID],[PersonID],[ApplicationRoleID],[RequestDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [PendingRoleRequest]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PendingRoleRequest_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__PendingRoleRequest_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PendingRoleRequest_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PendingRoleRequest_Delete;
        PRINT 'Dropped spGen__PendingRoleRequest_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PendingRoleRequest_Delete

   Description:  Deletes a record from table 'PendingRoleRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PendingRoleRequest_Delete
(
    @PendingRoleRequestID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [PendingRoleRequest]
    WHERE [PendingRoleRequestID] = @PendingRoleRequestID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PendingRoleRequest_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__PendingRoleRequest_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PendingRoleRequest_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PendingRoleRequest_Save;
        PRINT 'Dropped spGen__PendingRoleRequest_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PendingRoleRequest_Save

   Description:  Updates or Deletes a record In table 'PendingRoleRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PendingRoleRequest_Save
(
    @ErrText varchar(4000) output,
    @PendingRoleRequestID uniqueidentifier output,
    @PersonID uniqueidentifier,
    @ApplicationRoleID uniqueidentifier,
    @RequestDate datetime
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @PendingRoleRequestID = '00000000-0000-0000-0000-000000000000' SET @PendingRoleRequestID = NULL
    IF @PendingRoleRequestID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @PendingRoleRequestID = NewID()

                    INSERT
                    INTO [PendingRoleRequest]
                    (
                        [PendingRoleRequestID],
                        [PersonID],
                        [ApplicationRoleID],
                        [RequestDate],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @PendingRoleRequestID,
                        @PersonID,
                        @ApplicationRoleID,
                        @RequestDate,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [PendingRoleRequest]
                    SET
                    [PersonID] = @PersonID,
                    [ApplicationRoleID] = @ApplicationRoleID,
                    [RequestDate] = @RequestDate,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [PendingRoleRequestID] = @PendingRoleRequestID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PendingRoleRequest_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__PendingRoleRequest_Save Error on Creation'
GO




