/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertPersonParent
   Get rid of obsolete UpdatePersonParent
   Get rid of obsolete DeletePersonParent
   Get rid of obsolete SearchPersonParentByString
   Get rid of obsolete GetPersonParentByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertPersonParent') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertPersonParent;
        PRINT 'Dropped InsertPersonParent'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdatePersonParent') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdatePersonParent;
        PRINT 'Dropped UpdatePersonParent'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeletePersonParent') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeletePersonParent;
        PRINT 'Dropped DeletePersonParent'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchPersonParentByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchPersonParentByString;
        PRINT 'Dropped SearchPersonParentByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetPersonParentByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetPersonParentByID;
        PRINT 'Dropped GetPersonParentByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PersonParent_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PersonParent_GetByID;
        PRINT 'Dropped spGen__PersonParent_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PersonParent_GetByID

   Description:  Selects record(s) from table 'PersonParent'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PersonParent_GetByID
(
    @PersonParentID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [PersonParentID],[PersonID],[ParentID],[Relationship],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [PersonParent]
    WHERE [PersonParentID] = @PersonParentID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PersonParent_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__PersonParent_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PersonParent_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PersonParent_SearchByString;
        PRINT 'Dropped spGen__PersonParent_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PersonParent_SearchByString

   Description:  Selects a record from table 'PersonParent'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PersonParent_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [PersonParentID],[PersonID],[ParentID],[Relationship],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [PersonParent]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PersonParent_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__PersonParent_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PersonParent_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PersonParent_Delete;
        PRINT 'Dropped spGen__PersonParent_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PersonParent_Delete

   Description:  Deletes a record from table 'PersonParent'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PersonParent_Delete
(
    @PersonParentID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [PersonParent]
    WHERE [PersonParentID] = @PersonParentID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PersonParent_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__PersonParent_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__PersonParent_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__PersonParent_Save;
        PRINT 'Dropped spGen__PersonParent_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__PersonParent_Save

   Description:  Updates or Deletes a record In table 'PersonParent'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__PersonParent_Save
(
    @ErrText varchar(4000) output,
    @PersonParentID uniqueidentifier output,
    @PersonID uniqueidentifier,
    @ParentID uniqueidentifier,
    @Relationship varchar(50)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @PersonParentID = '00000000-0000-0000-0000-000000000000' SET @PersonParentID = NULL
    IF @PersonParentID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @PersonParentID = NewID()

                    INSERT
                    INTO [PersonParent]
                    (
                        [PersonParentID],
                        [PersonID],
                        [ParentID],
                        [Relationship],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @PersonParentID,
                        @PersonID,
                        @ParentID,
                        @Relationship,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [PersonParent]
                    SET
                    [PersonID] = @PersonID,
                    [ParentID] = @ParentID,
                    [Relationship] = @Relationship,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [PersonParentID] = @PersonParentID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__PersonParent_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__PersonParent_Save Error on Creation'
GO




