/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertProductPageSection
   Get rid of obsolete UpdateProductPageSection
   Get rid of obsolete DeleteProductPageSection
   Get rid of obsolete SearchProductPageSectionByString
   Get rid of obsolete GetProductPageSectionByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertProductPageSection') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertProductPageSection;
        PRINT 'Dropped InsertProductPageSection'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateProductPageSection') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateProductPageSection;
        PRINT 'Dropped UpdateProductPageSection'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteProductPageSection') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteProductPageSection;
        PRINT 'Dropped DeleteProductPageSection'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchProductPageSectionByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchProductPageSectionByString;
        PRINT 'Dropped SearchProductPageSectionByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetProductPageSectionByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetProductPageSectionByID;
        PRINT 'Dropped GetProductPageSectionByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageSection_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageSection_GetByID;
        PRINT 'Dropped spGen__ProductPageSection_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageSection_GetByID

   Description:  Selects record(s) from table 'ProductPageSection'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageSection_GetByID
(
    @ProductPageSectionID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ProductPageSectionID],[Title],[TemplateContent],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductPageSection]
    WHERE [ProductPageSectionID] = @ProductPageSectionID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageSection_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageSection_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageSection_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageSection_SearchByString;
        PRINT 'Dropped spGen__ProductPageSection_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageSection_SearchByString

   Description:  Selects a record from table 'ProductPageSection'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageSection_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ProductPageSectionID],[Title],[TemplateContent],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductPageSection]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageSection_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageSection_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageSection_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageSection_Delete;
        PRINT 'Dropped spGen__ProductPageSection_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageSection_Delete

   Description:  Deletes a record from table 'ProductPageSection'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageSection_Delete
(
    @ProductPageSectionID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ProductPageSection]
    WHERE [ProductPageSectionID] = @ProductPageSectionID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageSection_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageSection_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageSection_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageSection_Save;
        PRINT 'Dropped spGen__ProductPageSection_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageSection_Save

   Description:  Updates or Deletes a record In table 'ProductPageSection'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageSection_Save
(
    @ErrText varchar(4000) output,
    @ProductPageSectionID uniqueidentifier output,
    @Title varchar(50),
    @TemplateContent text
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ProductPageSectionID = '00000000-0000-0000-0000-000000000000' SET @ProductPageSectionID = NULL
    IF @ProductPageSectionID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ProductPageSectionID = NewID()

                    INSERT
                    INTO [ProductPageSection]
                    (
                        [ProductPageSectionID],
                        [Title],
                        [TemplateContent],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ProductPageSectionID,
                        @Title,
                        @TemplateContent,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ProductPageSection]
                    SET
                    [Title] = @Title,
                    [TemplateContent] = @TemplateContent,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ProductPageSectionID] = @ProductPageSectionID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageSection_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageSection_Save Error on Creation'
GO




