/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertProductPageDetail
   Get rid of obsolete UpdateProductPageDetail
   Get rid of obsolete DeleteProductPageDetail
   Get rid of obsolete SearchProductPageDetailByString
   Get rid of obsolete GetProductPageDetailByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertProductPageDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertProductPageDetail;
        PRINT 'Dropped InsertProductPageDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateProductPageDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateProductPageDetail;
        PRINT 'Dropped UpdateProductPageDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteProductPageDetail') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteProductPageDetail;
        PRINT 'Dropped DeleteProductPageDetail'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchProductPageDetailByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchProductPageDetailByString;
        PRINT 'Dropped SearchProductPageDetailByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetProductPageDetailByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetProductPageDetailByID;
        PRINT 'Dropped GetProductPageDetailByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageDetail_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageDetail_GetByID;
        PRINT 'Dropped spGen__ProductPageDetail_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageDetail_GetByID

   Description:  Selects record(s) from table 'ProductPageDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageDetail_GetByID
(
    @ProductPageDetailID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ProductPageDetailID],[ProductID],[ProductPageSectionID],[SortOrder],[BodyContent],[ExternalURL],[OnClick],[Disabled],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductPageDetail]
    WHERE [ProductPageDetailID] = @ProductPageDetailID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageDetail_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageDetail_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageDetail_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageDetail_SearchByString;
        PRINT 'Dropped spGen__ProductPageDetail_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageDetail_SearchByString

   Description:  Selects a record from table 'ProductPageDetail'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageDetail_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ProductPageDetailID],[ProductID],[ProductPageSectionID],[SortOrder],[BodyContent],[ExternalURL],[OnClick],[Disabled],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductPageDetail]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageDetail_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageDetail_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageDetail_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageDetail_Delete;
        PRINT 'Dropped spGen__ProductPageDetail_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageDetail_Delete

   Description:  Deletes a record from table 'ProductPageDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageDetail_Delete
(
    @ProductPageDetailID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ProductPageDetail]
    WHERE [ProductPageDetailID] = @ProductPageDetailID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageDetail_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageDetail_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductPageDetail_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductPageDetail_Save;
        PRINT 'Dropped spGen__ProductPageDetail_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductPageDetail_Save

   Description:  Updates or Deletes a record In table 'ProductPageDetail'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductPageDetail_Save
(
    @ErrText varchar(4000) output,
    @ProductPageDetailID uniqueidentifier output,
    @ProductID uniqueidentifier,
    @ProductPageSectionID uniqueidentifier,
    @SortOrder int,
    @BodyContent text,
    @ExternalURL varchar(256),
    @OnClick varchar(512),
    @Disabled bit
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ProductPageDetailID = '00000000-0000-0000-0000-000000000000' SET @ProductPageDetailID = NULL
    IF @ProductPageDetailID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ProductPageDetailID = NewID()

                    INSERT
                    INTO [ProductPageDetail]
                    (
                        [ProductPageDetailID],
                        [ProductID],
                        [ProductPageSectionID],
                        [SortOrder],
                        [BodyContent],
                        [ExternalURL],
                        [OnClick],
                        [Disabled],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ProductPageDetailID,
                        @ProductID,
                        @ProductPageSectionID,
                        @SortOrder,
                        @BodyContent,
                        @ExternalURL,
                        @OnClick,
                        @Disabled,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ProductPageDetail]
                    SET
                    [ProductID] = @ProductID,
                    [ProductPageSectionID] = @ProductPageSectionID,
                    [SortOrder] = @SortOrder,
                    [BodyContent] = @BodyContent,
                    [ExternalURL] = @ExternalURL,
                    [OnClick] = @OnClick,
                    [Disabled] = @Disabled,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ProductPageDetailID] = @ProductPageDetailID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductPageDetail_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductPageDetail_Save Error on Creation'
GO




