/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertProductModelWH
   Get rid of obsolete UpdateProductModelWH
   Get rid of obsolete DeleteProductModelWH
   Get rid of obsolete SearchProductModelWHByString
   Get rid of obsolete GetProductModelWHByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertProductModelWH') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertProductModelWH;
        PRINT 'Dropped InsertProductModelWH'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateProductModelWH') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateProductModelWH;
        PRINT 'Dropped UpdateProductModelWH'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteProductModelWH') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteProductModelWH;
        PRINT 'Dropped DeleteProductModelWH'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchProductModelWHByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchProductModelWHByString;
        PRINT 'Dropped SearchProductModelWHByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetProductModelWHByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetProductModelWHByID;
        PRINT 'Dropped GetProductModelWHByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductModelWH_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductModelWH_GetByID;
        PRINT 'Dropped spGen__ProductModelWH_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductModelWH_GetByID

   Description:  Selects record(s) from table 'ProductModelWH'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductModelWH_GetByID
(
    @ProductModelWHID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ProductModelWHID],[ProductID],[Model],[TanklessGas],[TanklessElectric],[TankGas],[TankElectic],[ManufacturedHousing],[Solar],[Indirect],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductModelWH]
    WHERE [ProductModelWHID] = @ProductModelWHID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductModelWH_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductModelWH_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductModelWH_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductModelWH_SearchByString;
        PRINT 'Dropped spGen__ProductModelWH_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductModelWH_SearchByString

   Description:  Selects a record from table 'ProductModelWH'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductModelWH_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ProductModelWHID],[ProductID],[Model],[TanklessGas],[TanklessElectric],[TankGas],[TankElectic],[ManufacturedHousing],[Solar],[Indirect],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductModelWH]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductModelWH_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductModelWH_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductModelWH_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductModelWH_Delete;
        PRINT 'Dropped spGen__ProductModelWH_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductModelWH_Delete

   Description:  Deletes a record from table 'ProductModelWH'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductModelWH_Delete
(
    @ProductModelWHID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ProductModelWH]
    WHERE [ProductModelWHID] = @ProductModelWHID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductModelWH_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductModelWH_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductModelWH_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductModelWH_Save;
        PRINT 'Dropped spGen__ProductModelWH_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductModelWH_Save

   Description:  Updates or Deletes a record In table 'ProductModelWH'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductModelWH_Save
(
    @ErrText varchar(4000) output,
    @ProductModelWHID uniqueidentifier output,
    @ProductID uniqueidentifier,
    @Model varchar(50),
    @TanklessGas bit,
    @TanklessElectric bit,
    @TankGas bit,
    @TankElectic bit,
    @ManufacturedHousing bit,
    @Solar bit,
    @Indirect bit
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ProductModelWHID = '00000000-0000-0000-0000-000000000000' SET @ProductModelWHID = NULL
    IF @ProductModelWHID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ProductModelWHID = NewID()

                    INSERT
                    INTO [ProductModelWH]
                    (
                        [ProductModelWHID],
                        [ProductID],
                        [Model],
                        [TanklessGas],
                        [TanklessElectric],
                        [TankGas],
                        [TankElectic],
                        [ManufacturedHousing],
                        [Solar],
                        [Indirect],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ProductModelWHID,
                        @ProductID,
                        @Model,
                        @TanklessGas,
                        @TanklessElectric,
                        @TankGas,
                        @TankElectic,
                        @ManufacturedHousing,
                        @Solar,
                        @Indirect,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ProductModelWH]
                    SET
                    [ProductID] = @ProductID,
                    [Model] = @Model,
                    [TanklessGas] = @TanklessGas,
                    [TanklessElectric] = @TanklessElectric,
                    [TankGas] = @TankGas,
                    [TankElectic] = @TankElectic,
                    [ManufacturedHousing] = @ManufacturedHousing,
                    [Solar] = @Solar,
                    [Indirect] = @Indirect,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ProductModelWHID] = @ProductModelWHID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductModelWH_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductModelWH_Save Error on Creation'
GO




