/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertRebateProgramMember
   Get rid of obsolete UpdateRebateProgramMember
   Get rid of obsolete DeleteRebateProgramMember
   Get rid of obsolete SearchRebateProgramMemberByString
   Get rid of obsolete GetRebateProgramMemberByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertRebateProgramMember') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertRebateProgramMember;
        PRINT 'Dropped InsertRebateProgramMember'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateRebateProgramMember') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateRebateProgramMember;
        PRINT 'Dropped UpdateRebateProgramMember'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteRebateProgramMember') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteRebateProgramMember;
        PRINT 'Dropped DeleteRebateProgramMember'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchRebateProgramMemberByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchRebateProgramMemberByString;
        PRINT 'Dropped SearchRebateProgramMemberByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetRebateProgramMemberByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetRebateProgramMemberByID;
        PRINT 'Dropped GetRebateProgramMemberByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RebateProgramMember_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RebateProgramMember_GetByID;
        PRINT 'Dropped spGen__RebateProgramMember_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RebateProgramMember_GetByID

   Description:  Selects record(s) from table 'RebateProgramMember'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RebateProgramMember_GetByID
(
    @RebateProgramMemberID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [RebateProgramMemberID],[RebateProgramID],[OrganizationID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [RebateProgramMember]
    WHERE [RebateProgramMemberID] = @RebateProgramMemberID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RebateProgramMember_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__RebateProgramMember_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RebateProgramMember_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RebateProgramMember_SearchByString;
        PRINT 'Dropped spGen__RebateProgramMember_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RebateProgramMember_SearchByString

   Description:  Selects a record from table 'RebateProgramMember'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RebateProgramMember_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [RebateProgramMemberID],[RebateProgramID],[OrganizationID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [RebateProgramMember]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RebateProgramMember_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__RebateProgramMember_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RebateProgramMember_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RebateProgramMember_Delete;
        PRINT 'Dropped spGen__RebateProgramMember_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RebateProgramMember_Delete

   Description:  Deletes a record from table 'RebateProgramMember'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RebateProgramMember_Delete
(
    @RebateProgramMemberID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [RebateProgramMember]
    WHERE [RebateProgramMemberID] = @RebateProgramMemberID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RebateProgramMember_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__RebateProgramMember_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RebateProgramMember_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RebateProgramMember_Save;
        PRINT 'Dropped spGen__RebateProgramMember_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RebateProgramMember_Save

   Description:  Updates or Deletes a record In table 'RebateProgramMember'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RebateProgramMember_Save
(
    @ErrText varchar(4000) output,
    @RebateProgramMemberID uniqueidentifier output,
    @RebateProgramID uniqueidentifier,
    @OrganizationID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @RebateProgramMemberID = '00000000-0000-0000-0000-000000000000' SET @RebateProgramMemberID = NULL
    IF @RebateProgramMemberID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @RebateProgramMemberID = NewID()

                    INSERT
                    INTO [RebateProgramMember]
                    (
                        [RebateProgramMemberID],
                        [RebateProgramID],
                        [OrganizationID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @RebateProgramMemberID,
                        @RebateProgramID,
                        @OrganizationID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [RebateProgramMember]
                    SET
                    [RebateProgramID] = @RebateProgramID,
                    [OrganizationID] = @OrganizationID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [RebateProgramMemberID] = @RebateProgramMemberID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RebateProgramMember_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__RebateProgramMember_Save Error on Creation'
GO




