/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertRheemWebSite
   Get rid of obsolete UpdateRheemWebSite
   Get rid of obsolete DeleteRheemWebSite
   Get rid of obsolete SearchRheemWebSiteByString
   Get rid of obsolete GetRheemWebSiteByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertRheemWebSite') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertRheemWebSite;
        PRINT 'Dropped InsertRheemWebSite'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateRheemWebSite') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateRheemWebSite;
        PRINT 'Dropped UpdateRheemWebSite'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteRheemWebSite') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteRheemWebSite;
        PRINT 'Dropped DeleteRheemWebSite'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchRheemWebSiteByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchRheemWebSiteByString;
        PRINT 'Dropped SearchRheemWebSiteByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetRheemWebSiteByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetRheemWebSiteByID;
        PRINT 'Dropped GetRheemWebSiteByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemWebSite_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemWebSite_GetByID;
        PRINT 'Dropped spGen__RheemWebSite_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemWebSite_GetByID

   Description:  Selects record(s) from table 'RheemWebSite'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemWebSite_GetByID
(
    @RheemWebSiteID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [RheemWebSiteID],[WebSiteName],[WebSiteURL],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [RheemWebSite]
    WHERE [RheemWebSiteID] = @RheemWebSiteID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemWebSite_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemWebSite_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemWebSite_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemWebSite_SearchByString;
        PRINT 'Dropped spGen__RheemWebSite_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemWebSite_SearchByString

   Description:  Selects a record from table 'RheemWebSite'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemWebSite_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [RheemWebSiteID],[WebSiteName],[WebSiteURL],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [RheemWebSite]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemWebSite_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemWebSite_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemWebSite_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemWebSite_Delete;
        PRINT 'Dropped spGen__RheemWebSite_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemWebSite_Delete

   Description:  Deletes a record from table 'RheemWebSite'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemWebSite_Delete
(
    @RheemWebSiteID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [RheemWebSite]
    WHERE [RheemWebSiteID] = @RheemWebSiteID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemWebSite_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemWebSite_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__RheemWebSite_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__RheemWebSite_Save;
        PRINT 'Dropped spGen__RheemWebSite_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__RheemWebSite_Save

   Description:  Updates or Deletes a record In table 'RheemWebSite'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__RheemWebSite_Save
(
    @ErrText varchar(4000) output,
    @RheemWebSiteID uniqueidentifier output,
    @WebSiteName varchar(50),
    @WebSiteURL varchar(50)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @RheemWebSiteID = '00000000-0000-0000-0000-000000000000' SET @RheemWebSiteID = NULL
    IF @RheemWebSiteID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @RheemWebSiteID = NewID()

                    INSERT
                    INTO [RheemWebSite]
                    (
                        [RheemWebSiteID],
                        [WebSiteName],
                        [WebSiteURL],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @RheemWebSiteID,
                        @WebSiteName,
                        @WebSiteURL,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [RheemWebSite]
                    SET
                    [WebSiteName] = @WebSiteName,
                    [WebSiteURL] = @WebSiteURL,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [RheemWebSiteID] = @RheemWebSiteID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__RheemWebSite_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__RheemWebSite_Save Error on Creation'
GO




