/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertVDMRebateProgram
   Get rid of obsolete UpdateVDMRebateProgram
   Get rid of obsolete DeleteVDMRebateProgram
   Get rid of obsolete SearchVDMRebateProgramByString
   Get rid of obsolete GetVDMRebateProgramByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertVDMRebateProgram') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertVDMRebateProgram;
        PRINT 'Dropped InsertVDMRebateProgram'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateVDMRebateProgram') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateVDMRebateProgram;
        PRINT 'Dropped UpdateVDMRebateProgram'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteVDMRebateProgram') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteVDMRebateProgram;
        PRINT 'Dropped DeleteVDMRebateProgram'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchVDMRebateProgramByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchVDMRebateProgramByString;
        PRINT 'Dropped SearchVDMRebateProgramByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetVDMRebateProgramByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetVDMRebateProgramByID;
        PRINT 'Dropped GetVDMRebateProgramByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__VDMRebateProgram_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__VDMRebateProgram_GetByID;
        PRINT 'Dropped spGen__VDMRebateProgram_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__VDMRebateProgram_GetByID

   Description:  Selects record(s) from table 'VDMRebateProgram'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__VDMRebateProgram_GetByID
(
    @VDMRebateProgramID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [VDMRebateProgramID],[OrganizationID],[ContractorName],[Model],[SerialNumber],[RebateType],[RebateAmount],[InvoiceNumber],[InvoiceDate],[CreationDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [VDMRebateProgram]
    WHERE [VDMRebateProgramID] = @VDMRebateProgramID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__VDMRebateProgram_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__VDMRebateProgram_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__VDMRebateProgram_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__VDMRebateProgram_SearchByString;
        PRINT 'Dropped spGen__VDMRebateProgram_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__VDMRebateProgram_SearchByString

   Description:  Selects a record from table 'VDMRebateProgram'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__VDMRebateProgram_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [VDMRebateProgramID],[OrganizationID],[ContractorName],[Model],[SerialNumber],[RebateType],[RebateAmount],[InvoiceNumber],[InvoiceDate],[CreationDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [VDMRebateProgram]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__VDMRebateProgram_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__VDMRebateProgram_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__VDMRebateProgram_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__VDMRebateProgram_Delete;
        PRINT 'Dropped spGen__VDMRebateProgram_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__VDMRebateProgram_Delete

   Description:  Deletes a record from table 'VDMRebateProgram'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__VDMRebateProgram_Delete
(
    @VDMRebateProgramID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [VDMRebateProgram]
    WHERE [VDMRebateProgramID] = @VDMRebateProgramID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__VDMRebateProgram_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__VDMRebateProgram_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__VDMRebateProgram_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__VDMRebateProgram_Save;
        PRINT 'Dropped spGen__VDMRebateProgram_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__VDMRebateProgram_Save

   Description:  Updates or Deletes a record In table 'VDMRebateProgram'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__VDMRebateProgram_Save
(
    @ErrText varchar(4000) output,
    @VDMRebateProgramID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @ContractorName varchar(50),
    @Model varchar(50),
    @SerialNumber varchar(50),
    @RebateType varchar(50),
    @RebateAmount float,
    @InvoiceNumber varchar(50),
    @InvoiceDate datetime,
    @CreationDate datetime
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @VDMRebateProgramID = '00000000-0000-0000-0000-000000000000' SET @VDMRebateProgramID = NULL
    IF @VDMRebateProgramID IS NULL
        BEGIN
            SELECT @UniqueRowCount = COUNT(1) FROM [VDMRebateProgram] where [SerialNumber] = @SerialNumber 
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = 'SerialNumber ' + Convert(varchar(36), @SerialNumber) + ' already exists'
                END
            ELSE
                BEGIN
                    SET @VDMRebateProgramID = NewID()

                    INSERT
                    INTO [VDMRebateProgram]
                    (
                        [VDMRebateProgramID],
                        [OrganizationID],
                        [ContractorName],
                        [Model],
                        [SerialNumber],
                        [RebateType],
                        [RebateAmount],
                        [InvoiceNumber],
                        [InvoiceDate],
                        [CreationDate],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @VDMRebateProgramID,
                        @OrganizationID,
                        @ContractorName,
                        @Model,
                        @SerialNumber,
                        @RebateType,
                        @RebateAmount,
                        @InvoiceNumber,
                        @InvoiceDate,
                        @CreationDate,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            -- check to see that there isn't another row like this one (assuming the unique index column(s) might have changed)
            SELECT @UniqueRowCount = COUNT(1) FROM [VDMRebateProgram] where [SerialNumber] = @SerialNumber  and [VDMRebateProgramID] <> @VDMRebateProgramID
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = 'SerialNumber ' + Convert(varchar(36), @SerialNumber) + ' already exists'
                END
            ELSE
                BEGIN
                    UPDATE [VDMRebateProgram]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [ContractorName] = @ContractorName,
                    [Model] = @Model,
                    [SerialNumber] = @SerialNumber,
                    [RebateType] = @RebateType,
                    [RebateAmount] = @RebateAmount,
                    [InvoiceNumber] = @InvoiceNumber,
                    [InvoiceDate] = @InvoiceDate,
                    [CreationDate] = @CreationDate,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [VDMRebateProgramID] = @VDMRebateProgramID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__VDMRebateProgram_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__VDMRebateProgram_Save Error on Creation'
GO




