/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertWebSiteChangeRequestTestimonial
   Get rid of obsolete UpdateWebSiteChangeRequestTestimonial
   Get rid of obsolete DeleteWebSiteChangeRequestTestimonial
   Get rid of obsolete SearchWebSiteChangeRequestTestimonialByString
   Get rid of obsolete GetWebSiteChangeRequestTestimonialByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertWebSiteChangeRequestTestimonial') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertWebSiteChangeRequestTestimonial;
        PRINT 'Dropped InsertWebSiteChangeRequestTestimonial'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateWebSiteChangeRequestTestimonial') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateWebSiteChangeRequestTestimonial;
        PRINT 'Dropped UpdateWebSiteChangeRequestTestimonial'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteWebSiteChangeRequestTestimonial') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteWebSiteChangeRequestTestimonial;
        PRINT 'Dropped DeleteWebSiteChangeRequestTestimonial'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchWebSiteChangeRequestTestimonialByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchWebSiteChangeRequestTestimonialByString;
        PRINT 'Dropped SearchWebSiteChangeRequestTestimonialByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetWebSiteChangeRequestTestimonialByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetWebSiteChangeRequestTestimonialByID;
        PRINT 'Dropped GetWebSiteChangeRequestTestimonialByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestTestimonial_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestTestimonial_GetByID;
        PRINT 'Dropped spGen__WebSiteChangeRequestTestimonial_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestTestimonial_GetByID

   Description:  Selects record(s) from table 'WebSiteChangeRequestTestimonial'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestTestimonial_GetByID
(
    @WebSiteChangeRequestTestimonialID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [WebSiteChangeRequestTestimonialID],[WebSiteChangeRequestID],[Testimonial],[TestimonialDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WebSiteChangeRequestTestimonial]
    WHERE [WebSiteChangeRequestTestimonialID] = @WebSiteChangeRequestTestimonialID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestTestimonial_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestTestimonial_SearchByString;
        PRINT 'Dropped spGen__WebSiteChangeRequestTestimonial_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestTestimonial_SearchByString

   Description:  Selects a record from table 'WebSiteChangeRequestTestimonial'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestTestimonial_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [WebSiteChangeRequestTestimonialID],[WebSiteChangeRequestID],[Testimonial],[TestimonialDate],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WebSiteChangeRequestTestimonial]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestTestimonial_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestTestimonial_Delete;
        PRINT 'Dropped spGen__WebSiteChangeRequestTestimonial_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestTestimonial_Delete

   Description:  Deletes a record from table 'WebSiteChangeRequestTestimonial'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestTestimonial_Delete
(
    @WebSiteChangeRequestTestimonialID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [WebSiteChangeRequestTestimonial]
    WHERE [WebSiteChangeRequestTestimonialID] = @WebSiteChangeRequestTestimonialID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestTestimonial_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestTestimonial_Save;
        PRINT 'Dropped spGen__WebSiteChangeRequestTestimonial_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestTestimonial_Save

   Description:  Updates or Deletes a record In table 'WebSiteChangeRequestTestimonial'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestTestimonial_Save
(
    @ErrText varchar(4000) output,
    @WebSiteChangeRequestTestimonialID uniqueidentifier output,
    @WebSiteChangeRequestID uniqueidentifier,
    @Testimonial varchar(512),
    @TestimonialDate datetime
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @WebSiteChangeRequestTestimonialID = '00000000-0000-0000-0000-000000000000' SET @WebSiteChangeRequestTestimonialID = NULL
    IF @WebSiteChangeRequestTestimonialID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @WebSiteChangeRequestTestimonialID = NewID()

                    INSERT
                    INTO [WebSiteChangeRequestTestimonial]
                    (
                        [WebSiteChangeRequestTestimonialID],
                        [WebSiteChangeRequestID],
                        [Testimonial],
                        [TestimonialDate],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @WebSiteChangeRequestTestimonialID,
                        @WebSiteChangeRequestID,
                        @Testimonial,
                        @TestimonialDate,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [WebSiteChangeRequestTestimonial]
                    SET
                    [WebSiteChangeRequestID] = @WebSiteChangeRequestID,
                    [Testimonial] = @Testimonial,
                    [TestimonialDate] = @TestimonialDate,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [WebSiteChangeRequestTestimonialID] = @WebSiteChangeRequestTestimonialID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestTestimonial_Save Error on Creation'
GO




