/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertWebSiteChangeRequestFeature
   Get rid of obsolete UpdateWebSiteChangeRequestFeature
   Get rid of obsolete DeleteWebSiteChangeRequestFeature
   Get rid of obsolete SearchWebSiteChangeRequestFeatureByString
   Get rid of obsolete GetWebSiteChangeRequestFeatureByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertWebSiteChangeRequestFeature') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertWebSiteChangeRequestFeature;
        PRINT 'Dropped InsertWebSiteChangeRequestFeature'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateWebSiteChangeRequestFeature') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateWebSiteChangeRequestFeature;
        PRINT 'Dropped UpdateWebSiteChangeRequestFeature'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteWebSiteChangeRequestFeature') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteWebSiteChangeRequestFeature;
        PRINT 'Dropped DeleteWebSiteChangeRequestFeature'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchWebSiteChangeRequestFeatureByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchWebSiteChangeRequestFeatureByString;
        PRINT 'Dropped SearchWebSiteChangeRequestFeatureByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetWebSiteChangeRequestFeatureByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetWebSiteChangeRequestFeatureByID;
        PRINT 'Dropped GetWebSiteChangeRequestFeatureByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestFeature_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestFeature_GetByID;
        PRINT 'Dropped spGen__WebSiteChangeRequestFeature_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestFeature_GetByID

   Description:  Selects record(s) from table 'WebSiteChangeRequestFeature'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestFeature_GetByID
(
    @WebSiteChangeRequestFeatureID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [WebSiteChangeRequestFeatureID],[WebSiteConfigFileID],[WebSiteChangeRequestID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WebSiteChangeRequestFeature]
    WHERE [WebSiteChangeRequestFeatureID] = @WebSiteChangeRequestFeatureID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestFeature_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestFeature_SearchByString;
        PRINT 'Dropped spGen__WebSiteChangeRequestFeature_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestFeature_SearchByString

   Description:  Selects a record from table 'WebSiteChangeRequestFeature'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestFeature_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [WebSiteChangeRequestFeatureID],[WebSiteConfigFileID],[WebSiteChangeRequestID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WebSiteChangeRequestFeature]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestFeature_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestFeature_Delete;
        PRINT 'Dropped spGen__WebSiteChangeRequestFeature_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestFeature_Delete

   Description:  Deletes a record from table 'WebSiteChangeRequestFeature'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestFeature_Delete
(
    @WebSiteChangeRequestFeatureID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [WebSiteChangeRequestFeature]
    WHERE [WebSiteChangeRequestFeatureID] = @WebSiteChangeRequestFeatureID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WebSiteChangeRequestFeature_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WebSiteChangeRequestFeature_Save;
        PRINT 'Dropped spGen__WebSiteChangeRequestFeature_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WebSiteChangeRequestFeature_Save

   Description:  Updates or Deletes a record In table 'WebSiteChangeRequestFeature'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WebSiteChangeRequestFeature_Save
(
    @ErrText varchar(4000) output,
    @WebSiteChangeRequestFeatureID uniqueidentifier output,
    @WebSiteConfigFileID uniqueidentifier,
    @WebSiteChangeRequestID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @WebSiteChangeRequestFeatureID = '00000000-0000-0000-0000-000000000000' SET @WebSiteChangeRequestFeatureID = NULL
    IF @WebSiteChangeRequestFeatureID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @WebSiteChangeRequestFeatureID = NewID()

                    INSERT
                    INTO [WebSiteChangeRequestFeature]
                    (
                        [WebSiteChangeRequestFeatureID],
                        [WebSiteConfigFileID],
                        [WebSiteChangeRequestID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @WebSiteChangeRequestFeatureID,
                        @WebSiteConfigFileID,
                        @WebSiteChangeRequestID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [WebSiteChangeRequestFeature]
                    SET
                    [WebSiteConfigFileID] = @WebSiteConfigFileID,
                    [WebSiteChangeRequestID] = @WebSiteChangeRequestID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [WebSiteChangeRequestFeatureID] = @WebSiteChangeRequestFeatureID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__WebSiteChangeRequestFeature_Save Error on Creation'
GO




