/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertWHAgentOrganization
   Get rid of obsolete UpdateWHAgentOrganization
   Get rid of obsolete DeleteWHAgentOrganization
   Get rid of obsolete SearchWHAgentOrganizationByString
   Get rid of obsolete GetWHAgentOrganizationByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertWHAgentOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertWHAgentOrganization;
        PRINT 'Dropped InsertWHAgentOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateWHAgentOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateWHAgentOrganization;
        PRINT 'Dropped UpdateWHAgentOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteWHAgentOrganization') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteWHAgentOrganization;
        PRINT 'Dropped DeleteWHAgentOrganization'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchWHAgentOrganizationByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchWHAgentOrganizationByString;
        PRINT 'Dropped SearchWHAgentOrganizationByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetWHAgentOrganizationByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetWHAgentOrganizationByID;
        PRINT 'Dropped GetWHAgentOrganizationByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WHAgentOrganization_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WHAgentOrganization_GetByID;
        PRINT 'Dropped spGen__WHAgentOrganization_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WHAgentOrganization_GetByID

   Description:  Selects record(s) from table 'WHAgentOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WHAgentOrganization_GetByID
(
    @WHAgentOrganizationID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [WHAgentOrganizationID],[OrganizationID],[PrimaryAddressID],[Retail],[Wholesale],[Disabled],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WHAgentOrganization]
    WHERE [WHAgentOrganizationID] = @WHAgentOrganizationID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WHAgentOrganization_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__WHAgentOrganization_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WHAgentOrganization_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WHAgentOrganization_SearchByString;
        PRINT 'Dropped spGen__WHAgentOrganization_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WHAgentOrganization_SearchByString

   Description:  Selects a record from table 'WHAgentOrganization'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WHAgentOrganization_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [WHAgentOrganizationID],[OrganizationID],[PrimaryAddressID],[Retail],[Wholesale],[Disabled],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [WHAgentOrganization]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WHAgentOrganization_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__WHAgentOrganization_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WHAgentOrganization_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WHAgentOrganization_Delete;
        PRINT 'Dropped spGen__WHAgentOrganization_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WHAgentOrganization_Delete

   Description:  Deletes a record from table 'WHAgentOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WHAgentOrganization_Delete
(
    @WHAgentOrganizationID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [WHAgentOrganization]
    WHERE [WHAgentOrganizationID] = @WHAgentOrganizationID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WHAgentOrganization_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__WHAgentOrganization_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__WHAgentOrganization_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__WHAgentOrganization_Save;
        PRINT 'Dropped spGen__WHAgentOrganization_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__WHAgentOrganization_Save

   Description:  Updates or Deletes a record In table 'WHAgentOrganization'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__WHAgentOrganization_Save
(
    @ErrText varchar(4000) output,
    @WHAgentOrganizationID uniqueidentifier output,
    @OrganizationID uniqueidentifier,
    @PrimaryAddressID uniqueidentifier,
    @Retail bit,
    @Wholesale bit,
    @Disabled bit
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @WHAgentOrganizationID = '00000000-0000-0000-0000-000000000000' SET @WHAgentOrganizationID = NULL
    IF @WHAgentOrganizationID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @WHAgentOrganizationID = NewID()

                    INSERT
                    INTO [WHAgentOrganization]
                    (
                        [WHAgentOrganizationID],
                        [OrganizationID],
                        [PrimaryAddressID],
                        [Retail],
                        [Wholesale],
                        [Disabled],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @WHAgentOrganizationID,
                        @OrganizationID,
                        @PrimaryAddressID,
                        @Retail,
                        @Wholesale,
                        @Disabled,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [WHAgentOrganization]
                    SET
                    [OrganizationID] = @OrganizationID,
                    [PrimaryAddressID] = @PrimaryAddressID,
                    [Retail] = @Retail,
                    [Wholesale] = @Wholesale,
                    [Disabled] = @Disabled,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [WHAgentOrganizationID] = @WHAgentOrganizationID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__WHAgentOrganization_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__WHAgentOrganization_Save Error on Creation'
GO




