/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

/* ------------------------------------------------------------
   Get rid of obsolete InsertWizard
   Get rid of obsolete UpdateWizard
   Get rid of obsolete DeleteWizard
   Get rid of obsolete SearchWizardByString
   Get rid of obsolete GetWizardByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertWizard') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertWizard;
        PRINT 'Dropped InsertWizard'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateWizard') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateWizard;
        PRINT 'Dropped UpdateWizard'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteWizard') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteWizard;
        PRINT 'Dropped DeleteWizard'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchWizardByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchWizardByString;
        PRINT 'Dropped SearchWizardByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetWizardByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetWizardByID;
        PRINT 'Dropped GetWizardByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__Wizard_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__Wizard_GetByID;
        PRINT 'Dropped spGen__Wizard_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__Wizard_GetByID

   Description:  Selects record(s) from table 'Wizard'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__Wizard_GetByID
(
    @WizardID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [WizardID],[WizardName],[IsRequired],[WizardCompleteID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [Wizard]
    WHERE [WizardID] = @WizardID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__Wizard_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__Wizard_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__Wizard_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__Wizard_SearchByString;
        PRINT 'Dropped spGen__Wizard_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__Wizard_SearchByString

   Description:  Selects a record from table 'Wizard'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__Wizard_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [WizardID],[WizardName],[IsRequired],[WizardCompleteID],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [Wizard]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__Wizard_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__Wizard_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__Wizard_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__Wizard_Delete;
        PRINT 'Dropped spGen__Wizard_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__Wizard_Delete

   Description:  Deletes a record from table 'Wizard'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__Wizard_Delete
(
    @WizardID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [Wizard]
    WHERE [WizardID] = @WizardID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__Wizard_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__Wizard_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__Wizard_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__Wizard_Save;
        PRINT 'Dropped spGen__Wizard_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__Wizard_Save

   Description:  Updates or Deletes a record In table 'Wizard'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__Wizard_Save
(
    @ErrText varchar(4000) output,
    @WizardID uniqueidentifier output,
    @WizardName varchar(250),
    @IsRequired bit,
    @WizardCompleteID uniqueidentifier
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @WizardID = '00000000-0000-0000-0000-000000000000' SET @WizardID = NULL
    IF @WizardID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @WizardID = NewID()

                    INSERT
                    INTO [Wizard]
                    (
                        [WizardID],
                        [WizardName],
                        [IsRequired],
                        [WizardCompleteID],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @WizardID,
                        @WizardName,
                        @IsRequired,
                        @WizardCompleteID,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [Wizard]
                    SET
                    [WizardName] = @WizardName,
                    [IsRequired] = @IsRequired,
                    [WizardCompleteID] = @WizardCompleteID,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [WizardID] = @WizardID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__Wizard_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__Wizard_Save Error on Creation'
GO




