Use rheem;

CREATE TABLE IF NOT EXISTS rps_condenser(
    condenserId int(11) NOT NULL AUTO_INCREMENT,
	ID int NULL,
	Model nvarchar(30) NULL,
	TradeName nvarchar(50) NULL,
	Series nvarchar(50) NULL,
	Tonnage nvarchar(15) NULL,
	Status smallint NULL,
	Refrigerant nvarchar(20) NULL,
	Stages smallint NULL,
	SystemType nvarchar(40) NULL,
	Appl nvarchar(40) NULL,
	Height nvarchar(50) NULL,
	Width nvarchar(50) NULL,
	Length nvarchar(50) NULL,
	Weight real NULL,
	NCircuits smallint NULL,
	ComprType nvarchar(35) NULL,
	NCompr smallint NULL,
	ODCFM smallint NULL,
	ODMtr nvarchar(25) NULL,
	ODFanType nvarchar(25) NULL,
	FanDia real NULL,
	NFans smallint NULL,
	FlowControl nvarchar(20) NULL,
	TubeMat nvarchar(20) NULL,
	FinMat nvarchar(20) NULL,
	ODCoilType nvarchar(15) NULL,
	ODFaceArea real NULL,
	ODRows smallint NULL,
	ODTubeDia nvarchar(20) NULL,
	ODTubeSpace nvarchar(20) NULL,
	ODFins smallint NULL,
	IDFlowDir nvarchar(20) NULL,
	IDCFM smallint NULL,
	IDMtr nvarchar(25) NULL,
	IDType nvarchar(25) NULL,
	IDFaceArea real NULL,
	IDRows smallint NULL,
	IDTubeDia nvarchar(25) NULL,
	IDTubeSpace nvarchar(25) NULL,
	IDFins smallint NULL,
	IDFlowControl nvarchar(25) NULL,
	IDTubeMat nvarchar(25) NULL,
	IDFinMat nvarchar(25) NULL,
	GasInput int NULL,
	GasOutput int NULL,
	NumStages smallint NULL,
	Efficiency real NULL,
	Voltage smallint NULL,
	VoltRange nvarchar(15) NULL,
	FLA real NULL,
	MCA real NULL,
	Fuse smallint NULL,
	LiquidConn nvarchar(15) NULL,
	SuctionConn nvarchar(15) NULL,
	Sound smallint NULL,
	LowSound smallint NULL,
	PRIMARY KEY (condenserId)
);

