Use rheem;

CREATE TABLE IF NOT EXISTS rps_air_hand(
    air_handId int(11) NOT NULL AUTO_INCREMENT,
	ID int NULL,
	Manuf nvarchar(25) NULL,
	ARIModel nvarchar(25) NULL,
	Model nvarchar(25) NULL,
	Series nvarchar(25) NULL,
	Tonnage nvarchar(25) NULL,
	Application nvarchar(25) NULL,
	Status smallint NULL,
	Refrigerant nvarchar(255) NULL,
	Drain nvarchar(15) NULL,
	Stages nvarchar(50) NULL,
	FilterSize real NULL,
	FlowDir nvarchar(16) NULL,
	ElecHtr nvarchar(16) NULL,
	AirflowHi smallint NULL,
	AirflowLo smallint NULL,
	MtrType nvarchar(25) NULL,
	MtrHP nvarchar(25) NULL,
	WheelType nvarchar(25) NULL,
	WheelSize nvarchar(25) NULL,
	CoilModel nvarchar(25) NULL,
	Phase smallint NULL,
	Frequency smallint NULL,
	VoltRange nvarchar(25) NULL,
	Voltage smallint NULL,
	FLA real NULL,
	MCA real NULL,
	Fuse smallint NULL,
	Height nvarchar(50) NULL,
	Width nvarchar(50) NULL,
	Depth nvarchar(50) NULL,
	Weight real NULL,
	LiquidConn nvarchar(15) NULL,
	SuctionConn nvarchar(15) NULL,
	PRIMARY KEY (air_handId)
);

