Use rheem;

CREATE TABLE IF NOT EXISTS rps_dxcoil(
    dxcoilId int(11) NOT NULL AUTO_INCREMENT,
	ID int NULL,
	ARIModel nvarchar(25) NULL,
	Tonnage nvarchar(10) NULL,
	Status smallint NULL,
	Refrigerant smallint NULL,
	Type nvarchar(25) NULL,
	Drain nvarchar(25) NULL,
	FlowControl nvarchar(20) NULL,
	Application nvarchar(25) NULL,
	FlowDir nvarchar(25) NULL,
	FaceArea real NULL,
	Rows smallint NULL,
	TubeDia nvarchar(20) NULL,
	TubeSpace nvarchar(50) NULL,
	Fins smallint NULL,
	FinType nvarchar(20) NULL,
	TubeMat nvarchar(20) NULL,
	FinMat nvarchar(20) NULL,
	Height nvarchar(25) NULL,
	Depth nvarchar(20) NULL,
	Width nvarchar(20) NULL,
	Weight real NULL,
	UHeight nvarchar(15) NULL,
	UDepth nvarchar(15) NULL,
	UWidth nvarchar(15) NULL,
	UWeight real NULL,
	OutWidth nvarchar(15) NULL,
	OutDepth nvarchar(15) NULL,
	LiquidConn nvarchar(15) NULL,
	SuctionConn nvarchar(15) NULL,
	PRIMARY KEY (dxcoilId)
);

