Use rheem;

CREATE TABLE IF NOT EXISTS ru_ahri(
	AHRIID INT NOT NULL AUTO_INCREMENT ,
	BrandName varchar(50) NOT NULL,
	ACorHP varchar(50) NOT NULL,
	AHRICertifiedRefNum varchar(50) NULL,
	ModelStatus varchar(50) NULL,
	ManufacturerType varchar(50) NULL,
	TradeBrandName varchar(50) NULL,
	OutdoorUnitManufacturer varchar(50) NULL,
	OutdoorUnitModel varchar(50) NULL,
	IndoorUnitManufacturer varchar(50) NULL,
	IndoorUnitModel varchar(50) NULL,
	FurnaceModel varchar(50) NULL,
	CoolingCapacityBTUH varchar(50) NULL,
	CoolingEER varchar(50) NULL,
	CoolingSEER varchar(50) NULL,
	HighHeating47FCapacityBtuh varchar(50) NULL,
	HighHeating47FHSPF varchar(50) NULL,
	LowHeating17FCapacityBtuh varchar(50) NULL,
	Phase varchar(50) NULL,
	ARIType varchar(50) NULL,
	HSVTC varchar(50) NULL,
	ExclusivelyforExport varchar(50) NULL,
	EstCoolingCost varchar(50) NULL,
	EstHeatingCost varchar(50) NULL,
	EligibleforFederalTaxCredit varchar(50) NULL,
	Field23 varchar(50) NULL,
	Field24 varchar(50) NULL,
	Field25 varchar(50) NULL,
	Field26 varchar(50) NULL,
	Field27 varchar(50) NULL,
	Field28 varchar(50) NULL,
	Field29 varchar(50) NULL,
	Field30 varchar(50) NULL,
	Field31 varchar(50) NULL,
	Field32 varchar(50) NULL,
	Field33 varchar(50) NULL,
	Field34 varchar(50) NULL,
	Field35 varchar(50) NULL,
	CreateDateTime__Gen datetime NULL,
	UpdateDateTime__Gen datetime NULL,	
	tempid varchar(64) NOT NULL,
    PRIMARY KEY (AHRIID)
);