Use rheem;

CREATE TABLE IF NOT EXISTS ru_productcategory(
	ProductCategoryID varchar(64) NOT NULL,
	CategoryName varchar(50) NOT NULL,
	Model bit NOT NULL DEFAULT 0,
	Market bit NOT NULL DEFAULT 0,
	Brand bit NOT NULL DEFAULT 0,
	Series bit NOT NULL DEFAULT 0,
	Description bit NOT NULL DEFAULT 0,
	GasEfficiency bit NOT NULL DEFAULT 0,
	HSPF bit NOT NULL DEFAULT 0,
	ComfortControl bit NOT NULL DEFAULT 0,
	ComfortControl2 bit NOT NULL DEFAULT 0,
	Gamma bit NOT NULL DEFAULT 0,
	SEER bit NOT NULL DEFAULT 0,
	Tonnages bit NOT NULL DEFAULT 0,
	CabinetSize bit NOT NULL DEFAULT 0,
	ARI210240 bit NOT NULL DEFAULT 0,
	UL bit NOT NULL DEFAULT 0,
	R410A bit NOT NULL DEFAULT 0,
	EnergyGuide bit NOT NULL DEFAULT 0,
	EnergyStar bit NOT NULL DEFAULT 0,
	EnergyMiser bit NOT NULL DEFAULT 0,
	CSA bit NOT NULL DEFAULT 0,
	SACC bit NOT NULL DEFAULT 0,
	EIL bit NOT NULL DEFAULT 0,
	NSF bit NOT NULL DEFAULT 0,
	HLW bit NOT NULL DEFAULT 0,
	SCAQMD bit NOT NULL DEFAULT 0,
	ProductCopy bit NOT NULL DEFAULT 0,
	VirtualTourText bit NOT NULL DEFAULT 0,
	WarrantyText bit NOT NULL DEFAULT 0,
	TankWarranty bit NOT NULL DEFAULT 0,
	PartsWarranty bit NOT NULL DEFAULT 0,
	LaborWarranty bit NOT NULL DEFAULT 0,
	HeatExchangeWarranty bit NOT NULL DEFAULT 0,
	compressorWarranty bit NOT NULL DEFAULT 0,
	ExtendedWarranty bit NOT NULL DEFAULT 0,
	DisplayOnBHPG bit NOT NULL DEFAULT 0,
	DRHorton bit NOT NULL DEFAULT 0,
	GallonCapacity bit NOT NULL DEFAULT 0,
	TaxCredit bit NOT NULL DEFAULT 0,
	TaxCreditText bit NOT NULL DEFAULT 0,
	Gas bit NOT NULL DEFAULT 0,
	Electric bit NOT NULL DEFAULT 0,
	Tankless bit NOT NULL DEFAULT 0,
	Solar bit NOT NULL DEFAULT 0,
	SortOrder bit NOT NULL DEFAULT 0,
	ProductSystem bit NOT NULL DEFAULT 0,
	Common bit NOT NULL DEFAULT 0,
	AgencyApprovals bit NOT NULL DEFAULT 0,
	EfficiencyRange bit NOT NULL DEFAULT 0,
	ContractorFAB bit NOT NULL DEFAULT 0,
	CreateDateTime__Gen datetime NULL,
	UpdateDateTime__Gen datetime NULL,
    PRIMARY KEY (ProductCategoryID)
);

