Use econet;

CREATE TABLE IF NOT EXISTS country(
	CountryId INT NOT NULL AUTO_INCREMENT ,
	CountryName varchar(50) NOT NULL,
	PRIMARY KEY (CountryId));

	call rheem.AddColumnIfNotExists('econet', 'country', 'CountryCode',  'varchar(2) NOT NULL');
	call rheem.AddColumnIfNotExists('econet', 'country', 'IsActive',  'bit NOT NULL');
	call rheem.AddColumnIfNotExists('econet', 'country', 'UpdateDateTime__Gen',  'datetime NOT NULL');
	call rheem.AddColumnIfNotExists('econet', 'country', 'CreateDateTime__Gen',  'datetime NOT NULL');


call rheem.CreateIndexIfNotExists('econet', 'Country_idx1', 'country', 'CountryName', null);
call rheem.CreateIndexIfNotExists('econet', 'Country_idx2', 'country', 'CountryCode', null);

INSERT IGNORE INTO country SET CountryId = 1, IsActive = 1, CountryCode='AF', CountryName = 'Afghanistan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 2, IsActive = 1, CountryCode='AL', CountryName = 'Albania', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 3, IsActive = 1, CountryCode='DZ', CountryName = 'Algeria', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 4, IsActive = 1, CountryCode='AS', CountryName = 'American Samoa', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 5, IsActive = 1, CountryCode='AD', CountryName = 'Andorra', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 6, IsActive = 1, CountryCode='AO', CountryName = 'Angola', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 7, IsActive = 1, CountryCode='AI', CountryName = 'Anguilla', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 8, IsActive = 1, CountryCode='AQ', CountryName = 'Antarctica', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 9, IsActive = 1, CountryCode='AG', CountryName = 'Antigua and Barbuda', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 10, IsActive = 1, CountryCode='AR', CountryName = 'Argentina', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 11, IsActive = 1, CountryCode='AM', CountryName = 'Armenia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 12, IsActive = 1, CountryCode='AW', CountryName = 'Aruba', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 13, IsActive = 1, CountryCode='AU', CountryName = 'Australia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 14, IsActive = 1, CountryCode='AT', CountryName = 'Austria', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 15, IsActive = 1, CountryCode='AZ', CountryName = 'Azerbaijan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 16, IsActive = 1, CountryCode='BH', CountryName = 'Bahrain', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 17, IsActive = 1, CountryCode='BD', CountryName = 'Bangladesh', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 18, IsActive = 1, CountryCode='BB', CountryName = 'Barbados', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 19, IsActive = 1, CountryCode='BY', CountryName = 'Belarus', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 20, IsActive = 1, CountryCode='BE', CountryName = 'Belgium', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 21, IsActive = 1, CountryCode='BZ', CountryName = 'Belize', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 22, IsActive = 1, CountryCode='BJ', CountryName = 'Benin', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 23, IsActive = 1, CountryCode='BM', CountryName = 'Bermuda', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 24, IsActive = 1, CountryCode='BT', CountryName = 'Bhutan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 25, IsActive = 1, CountryCode='BO', CountryName = 'Bolivia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 26, IsActive = 1, CountryCode='BA', CountryName = 'Bosnia and Herzegovina', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 27, IsActive = 1, CountryCode='BW', CountryName = 'Botswana', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 28, IsActive = 1, CountryCode='BV', CountryName = 'Bouvet Island', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 29, IsActive = 1, CountryCode='BR', CountryName = 'Brazil', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 30, IsActive = 1, CountryCode='IO', CountryName = 'British Indian Ocean Territory', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 31, IsActive = 1, CountryCode='VG', CountryName = 'British Virgin Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 32, IsActive = 1, CountryCode='BN', CountryName = 'Brunei', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 33, IsActive = 1, CountryCode='BG', CountryName = 'Bulgaria', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 34, IsActive = 1, CountryCode='BF', CountryName = 'Burkina Faso', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 35, IsActive = 1, CountryCode='BI', CountryName = 'Burundi', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 36, IsActive = 1, CountryCode='CI', CountryName = 'Côte d''Ivoire', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 37, IsActive = 1, CountryCode='KH', CountryName = 'Cambodia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 38, IsActive = 1, CountryCode='CM', CountryName = 'Cameroon', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 39, IsActive = 1, CountryCode='CA', CountryName = 'Canada', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 40, IsActive = 1, CountryCode='CV', CountryName = 'Cape Verde', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 41, IsActive = 1, CountryCode='KY', CountryName = 'Cayman Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 42, IsActive = 1, CountryCode='CF', CountryName = 'Central African Republic', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 43, IsActive = 1, CountryCode='TD', CountryName = 'Chad', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 44, IsActive = 1, CountryCode='CL', CountryName = 'Chile', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 45, IsActive = 1, CountryCode='CN', CountryName = 'China', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 46, IsActive = 1, CountryCode='CX', CountryName = 'Christmas Island', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 47, IsActive = 1, CountryCode='CC', CountryName = 'Cocos (Keeling) Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 48, IsActive = 1, CountryCode='CO', CountryName = 'Colombia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 49, IsActive = 1, CountryCode='KM', CountryName = 'Comoros', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 50, IsActive = 1, CountryCode='CG', CountryName = 'Congo', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 51, IsActive = 1, CountryCode='CK', CountryName = 'Cook Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 52, IsActive = 1, CountryCode='CR', CountryName = 'Costa Rica', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 53, IsActive = 1, CountryCode='HR', CountryName = 'Croatia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 54, IsActive = 1, CountryCode='CU', CountryName = 'Cuba', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 55, IsActive = 1, CountryCode='CY', CountryName = 'Cyprus', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 56, IsActive = 1, CountryCode='CZ', CountryName = 'Czech Republic', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 57, IsActive = 1, CountryCode='CD', CountryName = 'Democratic Republic of the Congo', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 58, IsActive = 1, CountryCode='DK', CountryName = 'Denmark', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 59, IsActive = 1, CountryCode='DJ', CountryName = 'Djibouti', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 60, IsActive = 1, CountryCode='DM', CountryName = 'Dominica', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 61, IsActive = 1, CountryCode='DO', CountryName = 'Dominican Republic', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 62, IsActive = 1, CountryCode='TP', CountryName = 'East Timor', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 63, IsActive = 1, CountryCode='EC', CountryName = 'Ecuador', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 64, IsActive = 1, CountryCode='EG', CountryName = 'Egypt', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 65, IsActive = 1, CountryCode='SV', CountryName = 'El Salvador', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 66, IsActive = 1, CountryCode='GQ', CountryName = 'Equatorial Guinea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 67, IsActive = 1, CountryCode='ER', CountryName = 'Eritrea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 68, IsActive = 1, CountryCode='EE', CountryName = 'Estonia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 69, IsActive = 1, CountryCode='ET', CountryName = 'Ethiopia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 70, IsActive = 1, CountryCode='FO', CountryName = 'Faeroe Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 71, IsActive = 1, CountryCode='FK', CountryName = 'Falkland Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 72, IsActive = 1, CountryCode='FJ', CountryName = 'Fiji', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 73, IsActive = 1, CountryCode='FI', CountryName = 'Finland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 74, IsActive = 1, CountryCode='MK', CountryName = 'Former Yugoslav Republic of Macedonia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 75, IsActive = 1, CountryCode='FR', CountryName = 'France', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 76, IsActive = 1, CountryCode='FX', CountryName = 'France, Metropolitan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 77, IsActive = 1, CountryCode='GF', CountryName = 'French Guiana', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 78, IsActive = 1, CountryCode='PF', CountryName = 'French Polynesia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 79, IsActive = 1, CountryCode='TF', CountryName = 'French Southern Territories', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 80, IsActive = 1, CountryCode='GA', CountryName = 'Gabon', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 81, IsActive = 1, CountryCode='GE', CountryName = 'Georgia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 82, IsActive = 1, CountryCode='DE', CountryName = 'Germany', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 83, IsActive = 1, CountryCode='GH', CountryName = 'Ghana', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 84, IsActive = 1, CountryCode='GI', CountryName = 'Gibraltar', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 85, IsActive = 1, CountryCode='GR', CountryName = 'Greece', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 86, IsActive = 1, CountryCode='GL', CountryName = 'Greenland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 87, IsActive = 1, CountryCode='GD', CountryName = 'Grenada', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 88, IsActive = 1, CountryCode='GP', CountryName = 'Guadeloupe', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 89, IsActive = 1, CountryCode='GU', CountryName = 'Guam', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 90, IsActive = 1, CountryCode='GT', CountryName = 'Guatemala', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 91, IsActive = 1, CountryCode='GN', CountryName = 'Guinea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 92, IsActive = 1, CountryCode='GW', CountryName = 'Guinea-Bissau', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 93, IsActive = 1, CountryCode='GY', CountryName = 'Guyana', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 94, IsActive = 1, CountryCode='HT', CountryName = 'Haiti', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 95, IsActive = 1, CountryCode='HM', CountryName = 'Heard and Mc Donald Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 96, IsActive = 1, CountryCode='HN', CountryName = 'Honduras', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 97, IsActive = 1, CountryCode='HK', CountryName = 'Hong Kong', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 98, IsActive = 1, CountryCode='HU', CountryName = 'Hungary', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 99, IsActive = 1, CountryCode='IS', CountryName = 'Iceland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 100, IsActive = 1, CountryCode='IN', CountryName = 'India', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 101, IsActive = 1, CountryCode='ID', CountryName = 'Indonesia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 102, IsActive = 1, CountryCode='IR', CountryName = 'Iran', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 103, IsActive = 1, CountryCode='IQ', CountryName = 'Iraq', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 104, IsActive = 1, CountryCode='IE', CountryName = 'Ireland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 105, IsActive = 1, CountryCode='IL', CountryName = 'Israel', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 106, IsActive = 1, CountryCode='IT', CountryName = 'Italy', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 107, IsActive = 1, CountryCode='JM', CountryName = 'Jamaica', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 108, IsActive = 1, CountryCode='JP', CountryName = 'Japan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 109, IsActive = 1, CountryCode='JO', CountryName = 'Jordan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 110, IsActive = 1, CountryCode='KZ', CountryName = 'Kazakhstan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 111, IsActive = 1, CountryCode='KE', CountryName = 'Kenya', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 112, IsActive = 1, CountryCode='KI', CountryName = 'Kiribati', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 113, IsActive = 1, CountryCode='KW', CountryName = 'Kuwait', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 114, IsActive = 1, CountryCode='KG', CountryName = 'Kyrgyzstan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 115, IsActive = 1, CountryCode='LA', CountryName = 'Laos', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 116, IsActive = 1, CountryCode='LV', CountryName = 'Latvia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 117, IsActive = 1, CountryCode='LB', CountryName = 'Lebanon', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 118, IsActive = 1, CountryCode='LS', CountryName = 'Lesotho', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 119, IsActive = 1, CountryCode='LR', CountryName = 'Liberia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 120, IsActive = 1, CountryCode='LY', CountryName = 'Libya', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 121, IsActive = 1, CountryCode='LI', CountryName = 'Liechtenstein', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 122, IsActive = 1, CountryCode='LT', CountryName = 'Lithuania', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 123, IsActive = 1, CountryCode='LU', CountryName = 'Luxembourg', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 124, IsActive = 1, CountryCode='MO', CountryName = 'Macau', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 125, IsActive = 1, CountryCode='MG', CountryName = 'Madagascar', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 126, IsActive = 1, CountryCode='MW', CountryName = 'Malawi', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 127, IsActive = 1, CountryCode='MY', CountryName = 'Malaysia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 128, IsActive = 1, CountryCode='MV', CountryName = 'Maldives', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 129, IsActive = 1, CountryCode='ML', CountryName = 'Mali', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 130, IsActive = 1, CountryCode='MT', CountryName = 'Mayotte', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 131, IsActive = 1, CountryCode='MH', CountryName = 'Marshall Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 132, IsActive = 1, CountryCode='MQ', CountryName = 'Martinique', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 133, IsActive = 1, CountryCode='MR', CountryName = 'Mauritania', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 134, IsActive = 1, CountryCode='MU', CountryName = 'Mauritius', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 135, IsActive = 1, CountryCode='MX', CountryName = 'Mexico', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 136, IsActive = 1, CountryCode='FM', CountryName = 'Micronesia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 137, IsActive = 1, CountryCode='MD', CountryName = 'Moldova', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 138, IsActive = 1, CountryCode='MC', CountryName = 'Monaco', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 139, IsActive = 1, CountryCode='MN', CountryName = 'Mongolia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 140, IsActive = 1, CountryCode='ME', CountryName = 'Montenegro', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 141, IsActive = 1, CountryCode='MS', CountryName = 'Montserrat', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 142, IsActive = 1, CountryCode='MA', CountryName = 'Morocco', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 143, IsActive = 1, CountryCode='MZ', CountryName = 'Mozambique', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 144, IsActive = 1, CountryCode='MM', CountryName = 'Myanmar', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 145, IsActive = 1, CountryCode='NA', CountryName = 'Namibia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 146, IsActive = 1, CountryCode='NR', CountryName = 'Nauru', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 147, IsActive = 1, CountryCode='NP', CountryName = 'Nepal', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 148, IsActive = 1, CountryCode='NL', CountryName = 'Netherlands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 149, IsActive = 1, CountryCode='AN', CountryName = 'Netherlands Antilles', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 150, IsActive = 1, CountryCode='NC', CountryName = 'New Caledonia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 151, IsActive = 1, CountryCode='NZ', CountryName = 'New Zealand', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 152, IsActive = 1, CountryCode='NI', CountryName = 'Nicaragua', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 153, IsActive = 1, CountryCode='NE', CountryName = 'Niger', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 154, IsActive = 1, CountryCode='NG', CountryName = 'Nigeria', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 155, IsActive = 1, CountryCode='NU', CountryName = 'Niue', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 156, IsActive = 1, CountryCode='NF', CountryName = 'Norfolk Island', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 157, IsActive = 1, CountryCode='KP', CountryName = 'North Korea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 158, IsActive = 1, CountryCode='MP', CountryName = 'Northern Marianas', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 159, IsActive = 1, CountryCode='NO', CountryName = 'Norway', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 160, IsActive = 1, CountryCode='OM', CountryName = 'Oman', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 161, IsActive = 1, CountryCode='PK', CountryName = 'Pakistan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 162, IsActive = 1, CountryCode='PW', CountryName = 'Palau', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 163, IsActive = 1, CountryCode='PA', CountryName = 'Panama', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 164, IsActive = 1, CountryCode='PG', CountryName = 'Papua New Guinea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 165, IsActive = 1, CountryCode='PY', CountryName = 'Paraguay', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 166, IsActive = 1, CountryCode='PE', CountryName = 'Peru', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 167, IsActive = 1, CountryCode='PH', CountryName = 'Philippines', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 168, IsActive = 1, CountryCode='PN', CountryName = 'Pitcairn Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 169, IsActive = 1, CountryCode='PL', CountryName = 'Poland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 170, IsActive = 1, CountryCode='PT', CountryName = 'Portugal', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 171, IsActive = 1, CountryCode='PR', CountryName = 'Puerto Rico', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 172, IsActive = 1, CountryCode='QA', CountryName = 'Qatar', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 173, IsActive = 1, CountryCode='RE', CountryName = 'Reunion', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 174, IsActive = 1, CountryCode='RO', CountryName = 'Romania', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 175, IsActive = 1, CountryCode='RU', CountryName = 'Russia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 176, IsActive = 1, CountryCode='RW', CountryName = 'Rwanda', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 177, IsActive = 1, CountryCode='ST', CountryName = 'São Tomé and Príncipe', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 178, IsActive = 1, CountryCode='SH', CountryName = 'Saint Helena', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 179, IsActive = 1, CountryCode='PM', CountryName = 'St. Pierre and Miquelon', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 180, IsActive = 1, CountryCode='KN', CountryName = 'Saint Kitts and Nevis', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 181, IsActive = 1, CountryCode='LC', CountryName = 'Saint Lucia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 182, IsActive = 1, CountryCode='VC', CountryName = 'Saint Vincent and the Grenadines', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 183, IsActive = 1, CountryCode='WS', CountryName = 'Samoa', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 184, IsActive = 1, CountryCode='SM', CountryName = 'San Marino', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 185, IsActive = 1, CountryCode='SA', CountryName = 'Saudi Arabia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 186, IsActive = 1, CountryCode='SN', CountryName = 'Senegal', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 187, IsActive = 1, CountryCode='RS', CountryName = 'Serbia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 188, IsActive = 1, CountryCode='SC', CountryName = 'Seychelles', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 189, IsActive = 1, CountryCode='SL', CountryName = 'Sierra Leone', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 190, IsActive = 1, CountryCode='SG', CountryName = 'Singapore', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 191, IsActive = 1, CountryCode='SK', CountryName = 'Slovakia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 192, IsActive = 1, CountryCode='SI', CountryName = 'Slovenia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 193, IsActive = 1, CountryCode='SB', CountryName = 'Solomon Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 194, IsActive = 1, CountryCode='SO', CountryName = 'Somalia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 195, IsActive = 1, CountryCode='ZA', CountryName = 'South Africa', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 196, IsActive = 1, CountryCode='GS', CountryName = 'South Georgia and the South Sandwich Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 197, IsActive = 1, CountryCode='KR', CountryName = 'South Korea', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 198, IsActive = 1, CountryCode='ES', CountryName = 'Spain', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 199, IsActive = 1, CountryCode='LK', CountryName = 'Sri Lanka', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 200, IsActive = 1, CountryCode='SD', CountryName = 'Sudan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 201, IsActive = 1, CountryCode='SR', CountryName = 'Suriname', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 202, IsActive = 1, CountryCode='SJ', CountryName = 'Svalbard and Jan Mayen Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 203, IsActive = 1, CountryCode='SZ', CountryName = 'Swaziland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 204, IsActive = 1, CountryCode='SE', CountryName = 'Sweden', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 205, IsActive = 1, CountryCode='CH', CountryName = 'Switzerland', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 206, IsActive = 1, CountryCode='SY', CountryName = 'Syria', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 207, IsActive = 1, CountryCode='TW', CountryName = 'Taiwan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 208, IsActive = 1, CountryCode='TJ', CountryName = 'Tajikistan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 209, IsActive = 1, CountryCode='TZ', CountryName = 'Tanzania', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 210, IsActive = 1, CountryCode='TH', CountryName = 'Thailand', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 211, IsActive = 1, CountryCode='BS', CountryName = 'The Bahamas', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 212, IsActive = 1, CountryCode='GM', CountryName = 'The Gambia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 213, IsActive = 1, CountryCode='TG', CountryName = 'Togo', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 214, IsActive = 1, CountryCode='TK', CountryName = 'Tokelau', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 215, IsActive = 1, CountryCode='TO', CountryName = 'Tonga', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 216, IsActive = 1, CountryCode='TT', CountryName = 'Trinidad and Tobago', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 217, IsActive = 1, CountryCode='TN', CountryName = 'Tunisia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 218, IsActive = 1, CountryCode='TR', CountryName = 'Turkey', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 219, IsActive = 1, CountryCode='TM', CountryName = 'Turkmenistan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 220, IsActive = 1, CountryCode='TC', CountryName = 'Turks and Caicos Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 221, IsActive = 1, CountryCode='TV', CountryName = 'Tuvalu', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 222, IsActive = 1, CountryCode='VI', CountryName = 'US Virgin Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 223, IsActive = 1, CountryCode='UG', CountryName = 'Uganda', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 224, IsActive = 1, CountryCode='UA', CountryName = 'Ukraine', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 225, IsActive = 1, CountryCode='AE', CountryName = 'United Arab Emirates', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 226, IsActive = 1, CountryCode='GB', CountryName = 'United Kingdom', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 227, IsActive = 1, CountryCode='US', CountryName = 'United States', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 228, IsActive = 1, CountryCode='UM', CountryName = 'United States Minor Outlying Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 229, IsActive = 1, CountryCode='UY', CountryName = 'Uruguay', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 230, IsActive = 1, CountryCode='UZ', CountryName = 'Uzbekistan', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 231, IsActive = 1, CountryCode='VU', CountryName = 'Vanuatu', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 232, IsActive = 1, CountryCode='VA', CountryName = 'Vatican City', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 233, IsActive = 1, CountryCode='VE', CountryName = 'Venezuela', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 234, IsActive = 1, CountryCode='VN', CountryName = 'Vietnam', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 235, IsActive = 1, CountryCode='WF', CountryName = 'Wallis and Futuna Islands', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 236, IsActive = 1, CountryCode='EH', CountryName = 'Western Sahara', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 237, IsActive = 1, CountryCode='YE', CountryName = 'Yemen', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 238, IsActive = 1, CountryCode='ZM', CountryName = 'Zambia', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();
INSERT IGNORE INTO country SET CountryId = 239, IsActive = 1, CountryCode='ZW', CountryName = 'Zimbabwe', UpdateDateTime__Gen = NOW(), CreateDateTime__Gen = NOW();