use [WaterHeaterDB]
GO

alter table mtmsInventory alter column partNumber varchar(40)
ALTER Table mtmsInventory alter column marketingModelNumber varchar(255)
ALTER Table mtmsInventory alter column warehouseNumber varchar(30)
ALTER Table mtmsInventory alter column warehouseState varchar(10)
ALTER Table mtmsInventory alter column fuelType varchar(20)
ALTER Table mtmsInventory alter column dutyType varchar(30)
ALTER Table mtmsInventory alter column massachusettsCode varchar(30)
ALTER Table mtmsInventory alter column thermostatType varchar(30)
ALTER Table mtmsInventory alter column voltage varchar(30)
ALTER Table mtmsInventory alter column phase varchar(30)
ALTER Table mtmsInventory alter column wiring varchar(30)
ALTER Table mtmsInventory alter column storageTank varchar(30)
ALTER Table mtmsInventory alter column pumpType varchar(30)
ALTER Table mtmsInventory alter column locationType varchar(30)

if NOT EXISTS(select * from sys.columns where Name = N'configString'  
            and Object_ID = Object_ID(N'mtmsInventory'))
    alter table mtmsInventory add configString varchar(255)
GO


alter table mtmsResInventory alter column partNumber varchar(40)
ALTER Table mtmsResInventory alter column marketingModelNumber varchar(255)
ALTER Table mtmsResInventory alter column warehouseNumber varchar(30)
ALTER Table mtmsResInventory alter column warehouseState varchar(10)
Alter Table mtmsResInventory alter column quantityOnHand varchar(20)
ALTER Table mtmsResInventory alter column energyType varchar(20)
ALTER Table mtmsResInventory alter column tradeBrand varchar(40)
ALTER Table mtmsResInventory alter column partDescription varchar(240)

alter table AccumCustomer2 alter column CustNumber varchar(30)
alter table AccumCustomer2 alter column CustName varchar(360)
alter table AccumCustomer2 alter column Addr_Line1 varchar(240)
alter table AccumCustomer2 alter column Addr_Line2 varchar(240)
alter table AccumCustomer2 alter column Addr_City varchar(60)
alter table AccumCustomer2 alter column Addr_State varchar(60)
alter table AccumCustomer2 alter column Addr_Zip varchar(60)
alter table AccumCustomer2 alter column ParentGroup varchar(150)
alter table AccumCustomer2 alter column SalesID varchar(30)
alter table AccumCustomer2 alter column Phone varchar(30)
alter table AccumCustomer2 alter column Fax varchar(30)
alter table AccumCustomer2 alter column CustTierID varchar(150)
alter table AccumCustomer2 alter column CusTierDesc varchar(360)
alter table AccumCustomer2 alter column RegionID varchar(30)
alter table AccumCustomer2 alter column RegionDesc varchar(30)


alter table AccumCustomer alter column CustNumber varchar(30)
alter table AccumCustomer alter column CustName varchar(360)
alter table AccumCustomer alter column Addr_Line1 varchar(240)
alter table AccumCustomer alter column Addr_Line2 varchar(240)
alter table AccumCustomer alter column Addr_City varchar(60)
alter table AccumCustomer alter column Addr_State varchar(60)
alter table AccumCustomer alter column Addr_Zip varchar(60)
alter table AccumCustomer alter column ParentGroup varchar(150)
alter table AccumCustomer alter column SalesID varchar(30)
alter table AccumCustomer alter column Phone varchar(30)
alter table AccumCustomer alter column Fax varchar(30)
alter table AccumCustomer alter column CustTierID varchar(150)
alter table AccumCustomer alter column CusTierDesc varchar(360)
alter table AccumCustomer alter column RegionID varchar(30)
alter table AccumCustomer alter column RegionDesc varchar(30)

alter table mtmsBOLSerialNumbers alter column ShipmentBOLNumber varchar(255)
alter table mtmsBOLSerialNumbers alter column RheemSalesOrderNumber varchar(255)
alter table mtmsBOLSerialNumbers alter column RheemSalesOrderLine varchar(255)
alter table mtmsBOLSerialNumbers alter column CustomerPurchaseOrderNumber varchar(255)
alter table mtmsBOLSerialNumbers alter column CustomerNumber varchar(255)
alter table mtmsBOLSerialNumbers alter column UPC varchar(255)
alter table mtmsBOLSerialNumbers alter column MarketingModel varchar(255)
alter table mtmsBOLSerialNumbers alter column BaseModel varchar(255)
alter table mtmsBOLSerialNumbers alter column Variant varchar(255)
alter table mtmsBOLSerialNumbers alter column SerialNumber varchar(255)
alter table mtmsBOLSerialNumbers alter column ShipName varchar(2400)
alter table mtmsBOLSerialNumbers alter column ShipAddress varchar(240)
alter table mtmsBOLSerialNumbers alter column ShipAddress2 varchar(240)
alter table mtmsBOLSerialNumbers alter column ShipCity varchar(255)
alter table mtmsBOLSerialNumbers alter column ShipState varchar(255)
alter table mtmsBOLSerialNumbers alter column ShipZip varchar(255)


