/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [Products]

/* ------------------------------------------------------------
   Get rid of obsolete InsertProductLiteratureDescription
   Get rid of obsolete UpdateProductLiteratureDescription
   Get rid of obsolete DeleteProductLiteratureDescription
   Get rid of obsolete SearchProductLiteratureDescriptionByString
   Get rid of obsolete GetProductLiteratureDescriptionByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertProductLiteratureDescription') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertProductLiteratureDescription;
        PRINT 'Dropped InsertProductLiteratureDescription'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateProductLiteratureDescription') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateProductLiteratureDescription;
        PRINT 'Dropped UpdateProductLiteratureDescription'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteProductLiteratureDescription') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteProductLiteratureDescription;
        PRINT 'Dropped DeleteProductLiteratureDescription'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchProductLiteratureDescriptionByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchProductLiteratureDescriptionByString;
        PRINT 'Dropped SearchProductLiteratureDescriptionByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetProductLiteratureDescriptionByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetProductLiteratureDescriptionByID;
        PRINT 'Dropped GetProductLiteratureDescriptionByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductLiteratureDescription_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductLiteratureDescription_GetByID;
        PRINT 'Dropped spGen__ProductLiteratureDescription_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductLiteratureDescription_GetByID

   Description:  Selects record(s) from table 'ProductLiteratureDescription'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductLiteratureDescription_GetByID
(
    @ProductLiteratureDescriptionID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [ProductLiteratureDescriptionID],[ProductID],[SeqNumber],[Description],[BriefDescription],[WarrantyDescription],[FullDescription],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductLiteratureDescription]
    WHERE [ProductLiteratureDescriptionID] = @ProductLiteratureDescriptionID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductLiteratureDescription_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductLiteratureDescription_SearchByString;
        PRINT 'Dropped spGen__ProductLiteratureDescription_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductLiteratureDescription_SearchByString

   Description:  Selects a record from table 'ProductLiteratureDescription'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductLiteratureDescription_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [ProductLiteratureDescriptionID],[ProductID],[SeqNumber],[Description],[BriefDescription],[WarrantyDescription],[FullDescription],[CreateDateTime__Gen],[UpdateDateTime__Gen]
    FROM [ProductLiteratureDescription]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductLiteratureDescription_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductLiteratureDescription_Delete;
        PRINT 'Dropped spGen__ProductLiteratureDescription_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductLiteratureDescription_Delete

   Description:  Deletes a record from table 'ProductLiteratureDescription'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductLiteratureDescription_Delete
(
    @ProductLiteratureDescriptionID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ProductLiteratureDescription]
    WHERE [ProductLiteratureDescriptionID] = @ProductLiteratureDescriptionID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__ProductLiteratureDescription_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__ProductLiteratureDescription_Save;
        PRINT 'Dropped spGen__ProductLiteratureDescription_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__ProductLiteratureDescription_Save

   Description:  Updates or Deletes a record In table 'ProductLiteratureDescription'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__ProductLiteratureDescription_Save
(
    @ErrText varchar(4000) output,
    @ProductLiteratureDescriptionID uniqueidentifier output,
    @ProductID uniqueidentifier,
    @SeqNumber int,
    @Description varchar(1024),
    @BriefDescription bit,
    @WarrantyDescription bit,
    @FullDescription bit
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @ProductLiteratureDescriptionID = '00000000-0000-0000-0000-000000000000' SET @ProductLiteratureDescriptionID = NULL
    IF @ProductLiteratureDescriptionID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @ProductLiteratureDescriptionID = NewID()

                    INSERT
                    INTO [ProductLiteratureDescription]
                    (
                        [ProductLiteratureDescriptionID],
                        [ProductID],
                        [SeqNumber],
                        [Description],
                        [BriefDescription],
                        [WarrantyDescription],
                        [FullDescription],
                        [CreateDateTime__Gen],
                        [UpdateDateTime__Gen]
                    )
                    VALUES
                    (
                        @ProductLiteratureDescriptionID,
                        @ProductID,
                        @SeqNumber,
                        @Description,
                        @BriefDescription,
                        @WarrantyDescription,
                        @FullDescription,
                        SYSDATETIME(),
                        SYSDATETIME()
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [ProductLiteratureDescription]
                    SET
                    [ProductID] = @ProductID,
                    [SeqNumber] = @SeqNumber,
                    [Description] = @Description,
                    [BriefDescription] = @BriefDescription,
                    [WarrantyDescription] = @WarrantyDescription,
                    [FullDescription] = @FullDescription,
                    [UpdateDateTime__Gen] = SYSDATETIME()
                    WHERE [ProductLiteratureDescriptionID] = @ProductLiteratureDescriptionID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__ProductLiteratureDescription_Save Error on Creation'
GO




