/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemDB]

/* ------------------------------------------------------------
   Get rid of obsolete InsertEC_CreditRebateAmounts
   Get rid of obsolete UpdateEC_CreditRebateAmounts
   Get rid of obsolete DeleteEC_CreditRebateAmounts
   Get rid of obsolete SearchEC_CreditRebateAmountsByString
   Get rid of obsolete GetEC_CreditRebateAmountsByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertEC_CreditRebateAmounts') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertEC_CreditRebateAmounts;
        PRINT 'Dropped InsertEC_CreditRebateAmounts'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateEC_CreditRebateAmounts') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateEC_CreditRebateAmounts;
        PRINT 'Dropped UpdateEC_CreditRebateAmounts'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteEC_CreditRebateAmounts') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteEC_CreditRebateAmounts;
        PRINT 'Dropped DeleteEC_CreditRebateAmounts'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchEC_CreditRebateAmountsByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchEC_CreditRebateAmountsByString;
        PRINT 'Dropped SearchEC_CreditRebateAmountsByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetEC_CreditRebateAmountsByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetEC_CreditRebateAmountsByID;
        PRINT 'Dropped GetEC_CreditRebateAmountsByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditRebateAmounts_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditRebateAmounts_GetByID;
        PRINT 'Dropped spGen__EC_CreditRebateAmounts_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__EC_CreditRebateAmounts_GetByID

   Description:  Selects record(s) from table 'EC_CreditRebateAmounts'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__EC_CreditRebateAmounts_GetByID
(
    @CreditRebateAmountsID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [CreditRebateAmountsID],[CreditRebateNamesID],[CreditProductDescriptionID],[RebateAmount]
    FROM [EC_CreditRebateAmounts]
    WHERE [CreditRebateAmountsID] = @CreditRebateAmountsID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditRebateAmounts_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditRebateAmounts_SearchByString;
        PRINT 'Dropped spGen__EC_CreditRebateAmounts_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__EC_CreditRebateAmounts_SearchByString

   Description:  Selects a record from table 'EC_CreditRebateAmounts'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__EC_CreditRebateAmounts_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [CreditRebateAmountsID],[CreditRebateNamesID],[CreditProductDescriptionID],[RebateAmount]
    FROM [EC_CreditRebateAmounts]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditRebateAmounts_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditRebateAmounts_Delete;
        PRINT 'Dropped spGen__EC_CreditRebateAmounts_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__EC_CreditRebateAmounts_Delete

   Description:  Deletes a record from table 'EC_CreditRebateAmounts'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__EC_CreditRebateAmounts_Delete
(
    @CreditRebateAmountsID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [EC_CreditRebateAmounts]
    WHERE [CreditRebateAmountsID] = @CreditRebateAmountsID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditRebateAmounts_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditRebateAmounts_Save;
        PRINT 'Dropped spGen__EC_CreditRebateAmounts_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__EC_CreditRebateAmounts_Save

   Description:  Updates or Deletes a record In table 'EC_CreditRebateAmounts'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__EC_CreditRebateAmounts_Save
(
    @ErrText varchar(4000) output,
    @CreditRebateAmountsID uniqueidentifier output,
    @CreditRebateNamesID uniqueidentifier,
    @CreditProductDescriptionID uniqueidentifier,
    @RebateAmount decimal(2,0)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @CreditRebateAmountsID = '00000000-0000-0000-0000-000000000000' SET @CreditRebateAmountsID = NULL
    IF @CreditRebateAmountsID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @CreditRebateAmountsID = NewID()

                    INSERT
                    INTO [EC_CreditRebateAmounts]
                    (
                        [CreditRebateAmountsID],
                        [CreditRebateNamesID],
                        [CreditProductDescriptionID],
                        [RebateAmount]
                    )
                    VALUES
                    (
                        @CreditRebateAmountsID,
                        @CreditRebateNamesID,
                        @CreditProductDescriptionID,
                        @RebateAmount
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [EC_CreditRebateAmounts]
                    SET
                    [CreditRebateNamesID] = @CreditRebateNamesID,
                    [CreditProductDescriptionID] = @CreditProductDescriptionID,
                    [RebateAmount] = @RebateAmount
                    WHERE [CreditRebateAmountsID] = @CreditRebateAmountsID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__EC_CreditRebateAmounts_Save Error on Creation'
GO




