/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemDB]

/* ------------------------------------------------------------
   Get rid of obsolete InsertEC_CreditCategoryNames
   Get rid of obsolete UpdateEC_CreditCategoryNames
   Get rid of obsolete DeleteEC_CreditCategoryNames
   Get rid of obsolete SearchEC_CreditCategoryNamesByString
   Get rid of obsolete GetEC_CreditCategoryNamesByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertEC_CreditCategoryNames') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertEC_CreditCategoryNames;
        PRINT 'Dropped InsertEC_CreditCategoryNames'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateEC_CreditCategoryNames') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateEC_CreditCategoryNames;
        PRINT 'Dropped UpdateEC_CreditCategoryNames'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteEC_CreditCategoryNames') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteEC_CreditCategoryNames;
        PRINT 'Dropped DeleteEC_CreditCategoryNames'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchEC_CreditCategoryNamesByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchEC_CreditCategoryNamesByString;
        PRINT 'Dropped SearchEC_CreditCategoryNamesByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetEC_CreditCategoryNamesByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetEC_CreditCategoryNamesByID;
        PRINT 'Dropped GetEC_CreditCategoryNamesByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditCategoryNames_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditCategoryNames_GetByID;
        PRINT 'Dropped spGen__EC_CreditCategoryNames_GetByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditCategoryNames_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditCategoryNames_SearchByString;
        PRINT 'Dropped spGen__EC_CreditCategoryNames_SearchByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditCategoryNames_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditCategoryNames_Delete;
        PRINT 'Dropped spGen__EC_CreditCategoryNames_Delete'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__EC_CreditCategoryNames_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__EC_CreditCategoryNames_Save;
        PRINT 'Dropped spGen__EC_CreditCategoryNames_Save'
    END
GO


