/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemUsers]

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteModelWarrantyRuleModelsByModelWarrantyRuleID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteModelWarrantyRuleModelsByModelWarrantyRuleID;
        PRINT 'Dropped DeleteModelWarrantyRuleModelsByModelWarrantyRuleID'
    END
GO



/* ------------------------------------------------------------
   PROCEDURE:    DeleteModelWarrantyRuleModelsByModelWarrantyRuleID

   Description:  Deletes all records from table 'ModelWarrantyRuleModel' for a spcific WarrantyRule

   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.DeleteModelWarrantyRuleModelsByModelWarrantyRuleID
(
    @ModelWarrantyRuleID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [ModelWarrantyRuleModel]
    WHERE [ModelWarrantyRuleID] = @ModelWarrantyRuleID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: DeleteModelWarrantyRuleModelsByModelWarrantyRuleID Succeeded'
Else PRINT 'Procedure Creation: DeleteModelWarrantyRuleModelsByModelWarrantyRuleID Error on Creation'
GO







