USE [rheemusers]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GetExceptionDashboardData]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[GetExceptionDashboardData]
GO

-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[GetExceptionDashboardData] 
    -- Add the parameters for the stored procedure here
    
AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON;

	-- Non-Fatal Exceptions in the last 6 months
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 180 THEN 1 ELSE 0 END ), 0)  AS DAYS180, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 150 THEN 1 ELSE 0 END ), 0)  AS DAYS150,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 120 THEN 1 ELSE 0 END ), 0)  AS DAYS120,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 90 THEN 1 ELSE 0 END ), 0)  AS DAYS90,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 60 THEN 1 ELSE 0 END ), 0)  AS DAYS60,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 30 THEN 1 ELSE 0 END ), 0)  AS DAYS30,
	  COUNT(*)  AS DAYS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=0

	-- Fatal Exceptions in the last 6 months
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 180 THEN 1 ELSE 0 END ), 0)  AS DAYS180, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 150 THEN 1 ELSE 0 END ), 0)  AS DAYS150,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 120 THEN 1 ELSE 0 END ), 0)  AS DAYS120,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 90 THEN 1 ELSE 0 END ), 0)  AS DAYS90,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 60 THEN 1 ELSE 0 END ), 0)  AS DAYS60,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 30 THEN 1 ELSE 0 END ), 0)  AS DAYS30,
	  COUNT(*)  AS DAYS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=1

	-- Non-Fatal Exceptions in the last month
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 28 THEN 1 ELSE 0 END ), 0)  AS WEEKS4, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 21 THEN 1 ELSE 0 END ), 0)  AS WEEKS3,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 14 THEN 1 ELSE 0 END ), 0)  AS WEEKS2,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ), 0)  AS WEEKS1,
	  COUNT(*)  AS WEEKS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=0

	-- Fatal Exceptions in the last month
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 28 THEN 1 ELSE 0 END ), 0)  AS WEEKS4, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 21 THEN 1 ELSE 0 END ), 0)  AS WEEKS3,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 14 THEN 1 ELSE 0 END ), 0)  AS WEEKS2,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ), 0)  AS WEEKS1,
	  COUNT(*)  AS WEEKS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=1

	-- Non-Fatal Exceptions in the last week
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ), 0)  AS DAYS7, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 6 THEN 1 ELSE 0 END ), 0)  AS DAYS6,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 5 THEN 1 ELSE 0 END ), 0)  AS DAYS5,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 4 THEN 1 ELSE 0 END ), 0)  AS DAYS4,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 3 THEN 1 ELSE 0 END ), 0)  AS DAYS3,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 2 THEN 1 ELSE 0 END ), 0)  AS DAYS2,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 1 THEN 1 ELSE 0 END ), 0)  AS DAYS1,
	  COUNT(*)  AS DAYS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=0

	-- Fatal Exceptions in the last week
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ), 0)  AS DAYS7, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 6 THEN 1 ELSE 0 END ), 0)  AS DAYS6,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 5 THEN 1 ELSE 0 END ), 0)  AS DAYS5,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 4 THEN 1 ELSE 0 END ), 0)  AS DAYS4,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 3 THEN 1 ELSE 0 END ), 0)  AS DAYS3,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 2 THEN 1 ELSE 0 END ), 0)  AS DAYS2,
	  ISNULL(SUM( CASE WHEN DATEDIFF(DAY, ErrDateTime, GETDATE()) > 1 THEN 1 ELSE 0 END ), 0)  AS DAYS1,
	  COUNT(*)  AS DAYS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=1

	-- Non-Fatal Exceptions in the last 24 hours
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 24 THEN 1 ELSE 0 END ),0)  AS HOURS24, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 23 THEN 1 ELSE 0 END ),0)  AS HOURS23, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 22 THEN 1 ELSE 0 END ),0)  AS HOURS22, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 21 THEN 1 ELSE 0 END ),0)  AS HOURS21, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 20 THEN 1 ELSE 0 END ),0)  AS HOURS20, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 19 THEN 1 ELSE 0 END ),0)  AS HOURS19, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 18 THEN 1 ELSE 0 END ),0)  AS HOURS18, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 17 THEN 1 ELSE 0 END ),0)  AS HOURS17, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 16 THEN 1 ELSE 0 END ),0)  AS HOURS16, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 15 THEN 1 ELSE 0 END ),0)  AS HOURS15, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 14 THEN 1 ELSE 0 END ),0)  AS HOURS14, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 13 THEN 1 ELSE 0 END ),0)  AS HOURS13, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 12 THEN 1 ELSE 0 END ),0)  AS HOURS12, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 11 THEN 1 ELSE 0 END ),0)  AS HOURS11, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 10 THEN 1 ELSE 0 END ),0)  AS HOURS10, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 9 THEN 1 ELSE 0 END ),0)  AS HOURS9, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 8 THEN 1 ELSE 0 END ),0)  AS HOURS8, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ),0)  AS HOURS7, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 6 THEN 1 ELSE 0 END ),0)  AS HOURS6, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 5 THEN 1 ELSE 0 END ),0)  AS HOURS5, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 4 THEN 1 ELSE 0 END ),0)  AS HOURS4, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 3 THEN 1 ELSE 0 END ),0)  AS HOURS3, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 2 THEN 1 ELSE 0 END ),0)  AS HOURS2, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 1 THEN 1 ELSE 0 END ),0)  AS HOURS1, 
	  COUNT(*)  AS HOURS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=0

	-- Fatal Exceptions in the last 24 hours
	SELECT  
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 24 THEN 1 ELSE 0 END ),0)  AS HOURS24, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 23 THEN 1 ELSE 0 END ),0)  AS HOURS23, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 22 THEN 1 ELSE 0 END ),0)  AS HOURS22, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 21 THEN 1 ELSE 0 END ),0)  AS HOURS21, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 20 THEN 1 ELSE 0 END ),0)  AS HOURS20, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 19 THEN 1 ELSE 0 END ),0)  AS HOURS19, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 18 THEN 1 ELSE 0 END ),0)  AS HOURS18, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 17 THEN 1 ELSE 0 END ),0)  AS HOURS17, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 16 THEN 1 ELSE 0 END ),0)  AS HOURS16, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 15 THEN 1 ELSE 0 END ),0)  AS HOURS15, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 14 THEN 1 ELSE 0 END ),0)  AS HOURS14, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 13 THEN 1 ELSE 0 END ),0)  AS HOURS13, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 12 THEN 1 ELSE 0 END ),0)  AS HOURS12, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 11 THEN 1 ELSE 0 END ),0)  AS HOURS11, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 10 THEN 1 ELSE 0 END ),0)  AS HOURS10, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 9 THEN 1 ELSE 0 END ),0)  AS HOURS9, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 8 THEN 1 ELSE 0 END ),0)  AS HOURS8, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 7 THEN 1 ELSE 0 END ),0)  AS HOURS7, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 6 THEN 1 ELSE 0 END ),0)  AS HOURS6, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 5 THEN 1 ELSE 0 END ),0)  AS HOURS5, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 4 THEN 1 ELSE 0 END ),0)  AS HOURS4, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 3 THEN 1 ELSE 0 END ),0)  AS HOURS3, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 2 THEN 1 ELSE 0 END ),0)  AS HOURS2, 
	  ISNULL(SUM( CASE WHEN DATEDIFF(HOUR, ErrDateTime, GETDATE()) > 1 THEN 1 ELSE 0 END ),0)  AS HOURS1, 
	  COUNT(*)  AS HOURS0
	FROM rheemusers..ExceptionLog WHERE FatalBit=1

	SELECT COUNT(*) As RepLogCount,TableName 
	FROM rheemusers..ReplicationLog 
	GROUP BY TableName
	ORDER BY COUNT(*) DESC

END
GO
