/*
'===============================================================================
' Generated by GenerateDataAndObjectLayer Version 1.0.0.0
'
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'===============================================================================

*/
USE [RheemParts]

/* ------------------------------------------------------------
   Get rid of obsolete InsertSureComfortContractorRequest
   Get rid of obsolete UpdateSureComfortContractorRequest
   Get rid of obsolete DeleteSureComfortContractorRequest
   Get rid of obsolete SearchSureComfortContractorRequestByString
   Get rid of obsolete GetSureComfortContractorRequestByID
   ------------------------------------------------------------ */
If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InsertSureComfortContractorRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE InsertSureComfortContractorRequest;
        PRINT 'Dropped InsertSureComfortContractorRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateSureComfortContractorRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE UpdateSureComfortContractorRequest;
        PRINT 'Dropped UpdateSureComfortContractorRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteSureComfortContractorRequest') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE DeleteSureComfortContractorRequest;
        PRINT 'Dropped DeleteSureComfortContractorRequest'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearchSureComfortContractorRequestByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE SearchSureComfortContractorRequestByString;
        PRINT 'Dropped SearchSureComfortContractorRequestByString'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GetSureComfortContractorRequestByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE GetSureComfortContractorRequestByID;
        PRINT 'Dropped GetSureComfortContractorRequestByID'
    END
GO

If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__SureComfortContractorRequest_GetByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__SureComfortContractorRequest_GetByID;
        PRINT 'Dropped spGen__SureComfortContractorRequest_GetByID'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__SureComfortContractorRequest_GetByID

   Description:  Selects record(s) from table 'SureComfortContractorRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__SureComfortContractorRequest_GetByID
(
    @SureComfortContractorRequestID uniqueidentifier

)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int

    Select [SureComfortContractorRequestID],[OrganizationName],[AddressLine1],[AddressLine2],[City],[State],[Postalcode],[CorporatePhone],[CorporateEmail],[ParentOrganizationID],[FirstName],[LastName],[UserName],[Title],[UserEmail],[CorporateFax],[Password]
    FROM [SureComfortContractorRequest]
    WHERE [SureComfortContractorRequestID] = @SureComfortContractorRequestID

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_GetByID Succeeded'
Else PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_GetByID Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__SureComfortContractorRequest_SearchByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__SureComfortContractorRequest_SearchByString;
        PRINT 'Dropped spGen__SureComfortContractorRequest_SearchByString'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__SureComfortContractorRequest_SearchByString

   Description:  Selects a record from table 'SureComfortContractorRequest'
                 And puts values into parameters

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__SureComfortContractorRequest_SearchByString
(
    @searchParam varchar(4000)
)

AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

    DECLARE @Err Int
    DECLARE @strSql varchar(4000)

    SET @strSql = ' Select [SureComfortContractorRequestID],[OrganizationName],[AddressLine1],[AddressLine2],[City],[State],[Postalcode],[CorporatePhone],[CorporateEmail],[ParentOrganizationID],[FirstName],[LastName],[UserName],[Title],[UserEmail],[CorporateFax],[Password]
    FROM [SureComfortContractorRequest]
    WHERE ' +  @searchParam

    EXEC(@strSql)

    --//We should NOT be using exec above.
    --//If params are NOT known, then be sure to clean sql
    --//If params are known, format like example below

    --IF @prodname IS NOT NULL
    --SELECT @sql = @sql + ' ProductName LIKE @prodname'
    --EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_SearchByString Succeeded'
Else PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_SearchByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__SureComfortContractorRequest_Delete') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__SureComfortContractorRequest_Delete;
        PRINT 'Dropped spGen__SureComfortContractorRequest_Delete'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__SureComfortContractorRequest_Delete

   Description:  Deletes a record from table 'SureComfortContractorRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__SureComfortContractorRequest_Delete
(
    @SureComfortContractorRequestID uniqueidentifier

)
AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
    DECLARE @Err Int


    DELETE FROM [SureComfortContractorRequest]
    WHERE [SureComfortContractorRequestID] = @SureComfortContractorRequestID


End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_Delete Succeeded'
Else PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_Delete Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('spGen__SureComfortContractorRequest_Save') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
        DROP PROCEDURE spGen__SureComfortContractorRequest_Save;
        PRINT 'Dropped spGen__SureComfortContractorRequest_Save'
    END
GO

/* ------------------------------------------------------------
   PROCEDURE:    spGen__SureComfortContractorRequest_Save

   Description:  Updates or Deletes a record In table 'SureComfortContractorRequest'

   Generated by GenerateDataAndObjectLayer Version 1.0.0.0
   ------------------------------------------------------------ */

CREATE PROCEDURE dbo.spGen__SureComfortContractorRequest_Save
(
    @ErrText varchar(4000) output,
    @SureComfortContractorRequestID uniqueidentifier output,
    @OrganizationName varchar(50),
    @AddressLine1 varchar(50),
    @AddressLine2 varchar(50),
    @City varchar(50),
    @State varchar(50),
    @Postalcode varchar(50),
    @CorporatePhone varchar(50),
    @CorporateEmail varchar(50),
    @ParentOrganizationID uniqueidentifier,
    @FirstName varchar(50),
    @LastName varchar(50),
    @UserName varchar(50),
    @Title varchar(50),
    @UserEmail varchar(50),
    @CorporateFax varchar(50),
    @Password varchar(50)
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN

    DECLARE @UniqueRowCount Int
    IF @SureComfortContractorRequestID = '00000000-0000-0000-0000-000000000000' SET @SureComfortContractorRequestID = NULL
    IF @SureComfortContractorRequestID IS NULL
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    SET @SureComfortContractorRequestID = NewID()

                    INSERT
                    INTO [SureComfortContractorRequest]
                    (
                        [SureComfortContractorRequestID],
                        [OrganizationName],
                        [AddressLine1],
                        [AddressLine2],
                        [City],
                        [State],
                        [Postalcode],
                        [CorporatePhone],
                        [CorporateEmail],
                        [ParentOrganizationID],
                        [FirstName],
                        [LastName],
                        [UserName],
                        [Title],
                        [UserEmail],
                        [CorporateFax],
                        [Password]
                    )
                    VALUES
                    (
                        @SureComfortContractorRequestID,
                        @OrganizationName,
                        @AddressLine1,
                        @AddressLine2,
                        @City,
                        @State,
                        @Postalcode,
                        @CorporatePhone,
                        @CorporateEmail,
                        @ParentOrganizationID,
                        @FirstName,
                        @LastName,
                        @UserName,
                        @Title,
                        @UserEmail,
                        @CorporateFax,
                        @Password
                    )
                END
        END
    ELSE
        BEGIN
            SET @UniqueRowCount = 0       -- No unique indexes exist for this table
            IF @UniqueRowCount > 0
                BEGIN
                    SET @ErrText = ''    -- No unique indexes exist for this table
                END
            ELSE
                BEGIN
                    UPDATE [SureComfortContractorRequest]
                    SET
                    [OrganizationName] = @OrganizationName,
                    [AddressLine1] = @AddressLine1,
                    [AddressLine2] = @AddressLine2,
                    [City] = @City,
                    [State] = @State,
                    [Postalcode] = @Postalcode,
                    [CorporatePhone] = @CorporatePhone,
                    [CorporateEmail] = @CorporateEmail,
                    [ParentOrganizationID] = @ParentOrganizationID,
                    [FirstName] = @FirstName,
                    [LastName] = @LastName,
                    [UserName] = @UserName,
                    [Title] = @Title,
                    [UserEmail] = @UserEmail,
                    [CorporateFax] = @CorporateFax,
                    [Password] = @Password
                    WHERE [SureComfortContractorRequestID] = @SureComfortContractorRequestID
                END
        END

End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_Save Succeeded'
Else PRINT 'Procedure Creation: spGen__SureComfortContractorRequest_Save Error on Creation'
GO




