

USE [motorSports2008]

/* 
------------------------------------------------------------
   Description:  Common stored procedures For table 'editRacingSchedule2011'
   
   AUTHOR:       Brian White - 5/9/2011 11:24:20 AM
   
   LEGAL :       Copyright 2011 - Rheem Manufacturing
   
   Generated by MyGeneration Version 1.3.0.9
------------------------------------------------------------ 
*/
   


If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('InserteditRacingSchedule2011') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
    BEGIN
	    DROP PROCEDURE InserteditRacingSchedule2011;
		PRINT 'Dropped InserteditRacingSchedule2011'
	END
GO

/* ------------------------------------------------------------
   PROCEDURE:    InserteditRacingSchedule2011
   
   Description:  Inserts a record into table 'editRacingSchedule2011'
   
   AUTHOR:       Rheem Manufacturing, Brian White - 5/9/2011 11:24:20 AM
   
   Generated by MyGeneration Version 1.3.0.9
   ------------------------------------------------------------ */

CREATE PROCEDURE InserteditRacingSchedule2011
(
	@raceNumber int = null output,
	@Date datetime, 
	@Race nvarchar(255) = null, 
	@City nvarchar(255) = null, 
	@State nvarchar(255) = null, 
	@Distributor_Host nvarchar(255) = null, 
	@Rheem nvarchar(255) = null, 
	@Ruud nvarchar(255) = null, 
	@Notes nvarchar(255) = null, 
	@costPerPerson varchar(50) = null, 
	@available bit, 
	@adminNotes varchar(255) = null, 
	@maxPeople int, 
	@tvRating varchar(255) = null, 
	@series varchar(50) = null, 
	@completed bit, 
	@Schedule ntext = null
)

AS
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
	DECLARE @Err Int
	

	INSERT
	INTO [editRacingSchedule2011]
	(
		[Date], 
		[Race], 
		[City], 
		[State], 
		[Distributor_Host], 
		[Rheem], 
		[Ruud], 
		[Notes], 
		[costPerPerson], 
		[available], 
		[adminNotes], 
		[maxPeople], 
		[tvRating], 
		[series], 
		[completed], 
		[Schedule]
	)
	VALUES
	(
		@Date, 
		@Race, 
		@City, 
		@State, 
		@Distributor_Host, 
		@Rheem, 
		@Ruud, 
		@Notes, 
		@costPerPerson, 
		@available, 
		@adminNotes, 
		@maxPeople, 
		@tvRating, 
		@series, 
		@completed, 
		@Schedule

	)

	SET @Err = @@Error
	SET @raceNumber = @@identity


	RETURN @Err
End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: InserteditRacingSchedule2011 Succeeded'
Else PRINT 'Procedure Creation: InserteditRacingSchedule2011 Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('GeteditRacingSchedule2011ByID') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
	BEGIN
		DROP PROCEDURE GeteditRacingSchedule2011ByID;
		PRINT 'Dropped GeteditRacingSchedule2011ByID'
	END
GO

/* ------------------------------------------------------------
   PROCEDURE:    GeteditRacingSchedule2011ByID
   
   Description:  Selects record(s) from table 'editRacingSchedule2011'
   
   AUTHOR:       Rheem Manufacturing, Brian White - 5/9/2011 11:24:20 AM
   
   Generated by MyGeneration Version 1.3.0.9
   ------------------------------------------------------------ */

CREATE PROCEDURE GeteditRacingSchedule2011ByID
(
	@raceNumber int

)
As
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	DECLARE @Err Int

	Select 	[raceNumber], [Date], [Race], [City], [State], [Distributor_Host], [Rheem], [Ruud], [Notes], [costPerPerson], [available], [adminNotes], [maxPeople], [tvRating], [series], [completed], [Schedule]
	FROM [editRacingSchedule2011]
	WHERE [raceNumber] = @raceNumber

	Set @Err = @@Error

	RETURN @Err
End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: GeteditRacingSchedule2011ByID Succeeded'
Else PRINT 'Procedure Creation: GeteditRacingSchedule2011ByID Error on Creation'
GO





If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('SearcheditRacingSchedule2011ByString') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
	BEGIN
		DROP PROCEDURE SearcheditRacingSchedule2011ByString;
		PRINT 'Dropped SearcheditRacingSchedule2011ByString'
	END
GO

/* ------------------------------------------------------------
   PROCEDURE:    SearcheditRacingSchedule2011ByString
   
   Description:  Selects a record from table 'editRacingSchedule2011'
   				 And puts values into parameters
   
   AUTHOR:       Rheem Manufacturing, Brian White - 5/9/2011 11:24:20 AM
   
   Generated by MyGeneration Version 1.3.0.9
   ------------------------------------------------------------ */

CREATE PROCEDURE SearcheditRacingSchedule2011ByString
(
	@searchParam varchar(4000)
)
As
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	DECLARE @Err Int
	DECLARE @strSql varchar(4000)
	
	SET @strSql = '	Select 	[raceNumber], [Date], [Race], [City], [State], [Distributor_Host], [Rheem], [Ruud], [Notes], [costPerPerson], [available], [adminNotes], [maxPeople], [tvRating], [series], [completed], [Schedule]
	FROM [editRacingSchedule2011]
	WHERE ' +  @searchParam

	EXEC(@strSql)
	
	--//We should NOT be using exec above.
	--//If params are NOT known, then be sure to clean sql
	--//If params are known, format like example below
	
	--IF @prodname IS NOT NULL
	--SELECT @sql = @sql + ' ProductName LIKE @prodname'
	--EXEC sp_executesql @sql, N'@prodname varchar(400)',@prodname
End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: SearcheditRacingSchedule2011ByString Succeeded'
Else PRINT 'Procedure Creation: SearcheditRacingSchedule2011ByString Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('UpdateeditRacingSchedule2011') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
	BEGIN
		DROP PROCEDURE UpdateeditRacingSchedule2011;
		PRINT 'Dropped UpdateeditRacingSchedule2011'
	END
GO

/* ------------------------------------------------------------
   PROCEDURE:    UpdateeditRacingSchedule2011
   
   Description:  Updates a record In table 'editRacingSchedule2011'
   
   AUTHOR:       Rheem Manufacturing, Brian White - 5/9/2011 11:24:20 AM
   
   Generated by MyGeneration Version 1.3.0.9
   ------------------------------------------------------------ */

CREATE PROCEDURE UpdateeditRacingSchedule2011
(
	@raceNumber int, 
	@Date datetime, 
	@Race nvarchar(255), 
	@City nvarchar(255), 
	@State nvarchar(255), 
	@Distributor_Host nvarchar(255), 
	@Rheem nvarchar(255), 
	@Ruud nvarchar(255), 
	@Notes nvarchar(255), 
	@costPerPerson varchar(50), 
	@available bit, 
	@adminNotes varchar(255), 
	@maxPeople int, 
	@tvRating varchar(255), 
	@series varchar(50), 
	@completed bit, 
	@Schedule ntext

)
As
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
	DECLARE @Err Int

	UPDATE [editRacingSchedule2011]
	SET
	[Date] = @Date, 
	[Race] = @Race, 
	[City] = @City, 
	[State] = @State, 
	[Distributor_Host] = @Distributor_Host, 
	[Rheem] = @Rheem, 
	[Ruud] = @Ruud, 
	[Notes] = @Notes, 
	[costPerPerson] = @costPerPerson, 
	[available] = @available, 
	[adminNotes] = @adminNotes, 
	[maxPeople] = @maxPeople, 
	[tvRating] = @tvRating, 
	[series] = @series, 
	[completed] = @completed, 
	[Schedule] = @Schedule

	WHERE [raceNumber] = @raceNumber

	Set @Err = @@Error

	RETURN @Err
End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: UpdateeditRacingSchedule2011 Succeeded'
Else PRINT 'Procedure Creation: UpdateeditRacingSchedule2011 Error on Creation'
GO




If EXISTS (Select * FROM SYSOBJECTS WHERE ID = OBJECT_ID('DeleteeditRacingSchedule2011') AND OBJECTPROPERTY(ID, 'IsProcedure') = 1)
	BEGIN
		DROP PROCEDURE DeleteeditRacingSchedule2011;
		PRINT 'Dropped DeleteeditRacingSchedule2011'
	END
GO

/* ------------------------------------------------------------
   PROCEDURE:    DeleteeditRacingSchedule2011
   
   Description:  Deletes a record from table 'editRacingSchedule2011'
   
   AUTHOR:       Rheem Manufacturing, Brian White - 5/9/2011 11:24:20 AM
   
   Generated by MyGeneration Version 1.3.0.9
   ------------------------------------------------------------ */

CREATE PROCEDURE DeleteeditRacingSchedule2011
(
	@raceNumber int

)
As
SET NOCOUNT ON
SET XACT_ABORT ON

BEGIN
	DECLARE @Err Int

	DELETE FROM [editRacingSchedule2011] 
	WHERE [raceNumber] = @raceNumber
		

	Set @Err = @@Error

	RETURN @Err
End
GO

-- Display the status of Proc creation
If @@Error = 0 PRINT 'Procedure Creation: DeleteeditRacingSchedule2011 Succeeded'
Else PRINT 'Procedure Creation: DeleteeditRacingSchedule2011 Error on Creation'
GO
		
		


