USE [RheemUsers]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_Menu_MenuType' AND object_id = OBJECT_ID ('Menu'))
DROP index [IDX_Menu_MenuType] on Menu
go

CREATE NONCLUSTERED INDEX [IDX_Menu_MenuType] ON [dbo].[Menu] 
(
	[MenuType] ASC, 
	[ParentID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

