'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Competition
    Public Property CompetitionId As Integer
    Public Property MonthlyCompetition As Boolean
    Public Property CompetitionName As String
    Public Property Year As Integer
    Public Property Month As String

    Public Overridable Property WineEntries As ICollection(Of WineEntry) = New HashSet(Of WineEntry)

End Class
