'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EnvironmentTable
    Public Property EnvironmentTableID As Integer
    Public Property EnvironmentVariableName As String
    Public Property EnvironmentVariableValue As String

End Class
